from hpa_mdo.structure.spar_model import (
    DualSparSection,
    compute_dual_spar_section,
    segments_to_elements,
    segment_boundaries_from_lengths,
    tube_area,
    tube_Ixx,
    tube_J,
)
from hpa_mdo.structure.optimizer import SparOptimizer, OptimizationResult
from hpa_mdo.structure.dual_beam_analysis import DualBeamAnalysisResult, run_dual_beam_analysis
from hpa_mdo.structure.material_proxy_catalog import (
    MaterialProxyCatalog,
    MaterialScalePackage,
    build_default_material_proxy_catalog,
    resolve_catalog_property_rows,
)
from hpa_mdo.structure.inverse_design import (
    INVERSE_MARGIN_NAMES,
    FrozenLoadInverseDesignResult,
    GroundClearanceMetrics,
    InverseDesignFeasibility,
    LoadedShapeMatchMetrics,
    ManufacturingMetrics,
    ShapeErrorMetrics,
    StructuralNodeShape,
    build_frozen_load_inverse_design,
    build_frozen_load_inverse_design_from_mainline,
    build_inverse_design_margins,
    build_target_loaded_shape,
    shape_to_dict,
    write_shape_csv_from_template,
)
from hpa_mdo.structure.dual_beam_mainline import (
    AnalysisModeName,
    LinkMode,
    RootBCMode,
    WireBCMode,
    run_dual_beam_mainline_analysis,
)

__all__ = [
    "DualSparSection",
    "compute_dual_spar_section",
    "segments_to_elements",
    "segment_boundaries_from_lengths",
    "tube_area",
    "tube_Ixx",
    "tube_J",
    "SparOptimizer",
    "OptimizationResult",
    "MaterialProxyCatalog",
    "MaterialScalePackage",
    "build_default_material_proxy_catalog",
    "resolve_catalog_property_rows",
    "INVERSE_MARGIN_NAMES",
    "StructuralNodeShape",
    "ShapeErrorMetrics",
    "LoadedShapeMatchMetrics",
    "GroundClearanceMetrics",
    "ManufacturingMetrics",
    "InverseDesignFeasibility",
    "FrozenLoadInverseDesignResult",
    "build_target_loaded_shape",
    "build_frozen_load_inverse_design",
    "build_frozen_load_inverse_design_from_mainline",
    "build_inverse_design_margins",
    "shape_to_dict",
    "write_shape_csv_from_template",
    "DualBeamAnalysisResult",
    "run_dual_beam_analysis",
    "AnalysisModeName",
    "LinkMode",
    "RootBCMode",
    "WireBCMode",
    "run_dual_beam_mainline_analysis",
]
