"""Minimal consumer-facing autoresearch helpers for HPA-MDO."""

from hpa_mdo.autoresearch.consumer import (
    EXPECTED_DECISION_SCHEMA_NAME,
    EXPECTED_DECISION_SCHEMA_VERSION,
    AutoresearchConsumerError,
    AutoresearchPrimaryConfig,
    AutoresearchPrimaryRun,
    build_primary_mass_score,
    build_producer_cli_argv,
    default_output_dir,
    load_primary_mass_run,
)
from hpa_mdo.autoresearch.history import (
    AutoresearchHistoryError,
    AutoresearchRunContext,
    AutoresearchRunRecord,
    append_run_record,
    build_failure_run_record,
    build_run_context,
    build_success_run_record,
    default_history_dir,
    latest_record_path,
    load_run_records,
    render_run_summary,
    run_records_path,
    summarize_run_records,
)

__all__ = [
    "EXPECTED_DECISION_SCHEMA_NAME",
    "EXPECTED_DECISION_SCHEMA_VERSION",
    "AutoresearchConsumerError",
    "AutoresearchHistoryError",
    "AutoresearchPrimaryConfig",
    "AutoresearchPrimaryRun",
    "AutoresearchRunContext",
    "AutoresearchRunRecord",
    "append_run_record",
    "build_primary_mass_score",
    "build_producer_cli_argv",
    "build_failure_run_record",
    "build_run_context",
    "build_success_run_record",
    "default_history_dir",
    "default_output_dir",
    "latest_record_path",
    "load_primary_mass_run",
    "load_run_records",
    "render_run_summary",
    "run_records_path",
    "summarize_run_records",
]
