jobs:
  - component: fairing_solid
    geometry: examples/fairing_solid/example.step
    out_dir: out/batch/fairing_solid_001
    global_min_size: 0.005
    global_max_size: 0.08

  - component: main_wing
    geometry: examples/wing/example.step
    out_dir: out/batch/main_wing_001
    global_min_size: 0.01
    global_max_size: 0.20
