"""ParaView visualisation script generator for CalculiX high-fidelity results.

Generates a self-contained ``pvpython`` script that opens the CalculiX
``.frd`` outputs (static + buckling modes) and configures:

    * WarpByVector displacement filter (adjustable warp scale)
    * Von Mises stress colormap on the static result
    * Eigenvalue magnitude colormap on each buckling mode
    * 3-column small-multiple layout for buckling modes (ParaView 5.11+)
    * Camera oriented along +X looking at the half-span mid-point

No ParaView installation is required to **generate** the script — only
plain Python string operations are used.  The resulting ``.py`` file is
run with ``pvpython <script>.py`` or loaded via  *File → Load State* after
changing the extension to ``.pvsm`` (not recommended; use pvpython directly).

Public API
----------
make_pvpython_script(frd_paths, out_py, *, warp_scale, show_modes, span_m)
    Write the pvpython script to *out_py*.

discover_frd_files(hifi_dir)
    Scan an output directory and return (static_frd, [buckle_frd, …]).
"""
from __future__ import annotations

from pathlib import Path
from typing import List, Optional, Tuple


# ---------------------------------------------------------------------------
# Script-generation helpers
# ---------------------------------------------------------------------------

_HEADER = """\
#!/usr/bin/env pvpython
# =============================================================================
# HPA-MDO High-Fidelity Visualisation
# Generated by hpa_mdo.hifi.paraview_state
#
# Run with:
#   pvpython {script_name}
#
# ParaView >= 5.11 required.
# =============================================================================
from paraview.simple import (
    CreateRenderView,
    CreateLayout,
    AssignViewToLayout,
    GetAnimationScene,
    GetActiveViewOrCreate,
    Hide,
    RenderAllViews,
    SaveScreenshot,
    Show,
    UpdatePipeline,
    _DisableFirstRenderCameraReset,
    OpenDataFile,
    WarpByVector,
    GetColorTransferFunction,
    GetOpacityTransferFunction,
    GetScalarBar,
)
import os

_DisableFirstRenderCameraReset()

# ── Helpers ────────────────────────────────────────────────────────────────

def _setup_vonmises_colormap(view, display):
    \"\"\"Apply a rainbow von Mises colour scale [0, σ_max].\"\"\"
    lut = GetColorTransferFunction("vonmises")
    lut.ApplyPreset("Rainbow Uniform", True)
    display.ColorArrayName = ["POINTS", "vonmises"]
    display.LookupTable = lut
    scalarbar = GetScalarBar(lut, view)
    scalarbar.Title = "von Mises stress [Pa]"
    scalarbar.ComponentTitle = ""
    scalarbar.Visibility = 1


def _setup_displacement_colormap(view, display):
    \"\"\"Apply a blue-to-red displacement magnitude colour scale.\"\"\"
    lut = GetColorTransferFunction("DISP")
    lut.ApplyPreset("Blue to Red Rainbow", True)
    display.ColorArrayName = ["POINTS", "DISP"]
    display.LookupTable = lut
    scalarbar = GetScalarBar(lut, view)
    scalarbar.Title = "Displacement [m]"
    scalarbar.ComponentTitle = "Magnitude"
    scalarbar.Visibility = 1


def _set_camera(view, span_m):
    \"\"\"Position camera for an HPA half-span wing.\"\"\"
    y_mid = span_m / 4.0          # mid-span in Y
    view.CameraFocalPoint  = [0.0, y_mid, 0.0]
    view.CameraPosition    = [y_mid * 2.5, y_mid, y_mid * 1.5]
    view.CameraViewUp      = [0.0, 0.0, 1.0]
    view.CameraParallelProjection = 0
    view.ResetCamera()

"""

_FOOTER = """\

# ── Finalise ───────────────────────────────────────────────────────────────
RenderAllViews()
print("[hpa-mdo] ParaView visualisation ready.")
"""


def _static_block(frd_path: str, warp_scale: float, span_m: float) -> str:
    """Return the pvpython snippet for the static analysis result."""
    return f"""\
# ── Static result ──────────────────────────────────────────────────────────
print("[hpa-mdo] Loading static result: {frd_path}")
static_reader = OpenDataFile({frd_path!r})
UpdatePipeline(proxy=static_reader)

static_warp = WarpByVector(Input=static_reader)
static_warp.Vectors = ["POINTS", "DISP"]
static_warp.ScaleFactor = {warp_scale!r}
UpdatePipeline(proxy=static_warp)

static_view = CreateRenderView()
static_layout = CreateLayout("Static Analysis")
AssignViewToLayout(view=static_view, layout=static_layout, hint=0)

static_disp_warp = Show(static_warp, static_view)
static_disp_warp.Representation = "Surface With Edges"
_setup_vonmises_colormap(static_view, static_disp_warp)

# Undeformed wireframe for reference
static_disp_raw = Show(static_reader, static_view)
static_disp_raw.Representation = "Wireframe"
static_disp_raw.AmbientColor = [0.5, 0.5, 0.5]
static_disp_raw.DiffuseColor = [0.5, 0.5, 0.5]
static_disp_raw.Opacity = 0.3

_set_camera(static_view, {span_m!r})
static_view.Update()

"""


def _buckle_block(
    buckle_paths: List[str],
    warp_scale: float,
    span_m: float,
    n_cols: int,
) -> str:
    """Return the pvpython snippet for all buckling modes."""
    if not buckle_paths:
        return "# No buckling results found.\n"

    n = len(buckle_paths)
    n_rows = (n + n_cols - 1) // n_cols

    lines: List[str] = [
        "# ── Buckling modes ────────────────────────────────────────────────────────\n",
        f"buckle_layout = CreateLayout('Buckling Modes ({n} modes)')\n",
        f"_n_rows, _n_cols = {n_rows}, {n_cols}\n",
        "buckle_views = []\n",
        "\n",
    ]

    for i, frd_path in enumerate(buckle_paths):
        row = i // n_cols
        col = i % n_cols
        mode_num = i + 1
        hint = row * n_cols + col   # layout split hint index

        lines.append(
            f"# Mode {mode_num}: {Path(frd_path).name}\n"
            f"_r{i} = OpenDataFile({frd_path!r})\n"
            f"UpdatePipeline(proxy=_r{i})\n"
            f"_w{i} = WarpByVector(Input=_r{i})\n"
            f"_w{i}.Vectors = ['POINTS', 'DISP']\n"
            f"_w{i}.ScaleFactor = {warp_scale!r}\n"
            f"UpdatePipeline(proxy=_w{i})\n"
            f"_v{i} = CreateRenderView()\n"
            f"AssignViewToLayout(view=_v{i}, layout=buckle_layout, hint={hint})\n"
            f"_d{i} = Show(_w{i}, _v{i})\n"
            f"_d{i}.Representation = 'Surface With Edges'\n"
            f"_setup_displacement_colormap(_v{i}, _d{i})\n"
            f"_set_camera(_v{i}, {span_m!r})\n"
            f"_v{i}.ViewSize = [400, 300]\n"
            f"buckle_views.append(_v{i})\n\n"
        )

    return "".join(lines)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def make_pvpython_script(
    frd_paths: List[Path | str],
    out_py: Path | str,
    *,
    warp_scale: float = 10.0,
    show_modes: int = 6,
    span_m: float = 16.5,
    n_buckle_cols: int = 3,
) -> Path:
    """Generate a ``pvpython`` visualisation script.

    Parameters
    ----------
    frd_paths : list of Path / str
        CalculiX result files.  The **first** path is treated as the static
        analysis result; remaining paths are buckling modes (sorted).
        Caller may pass just one path for static-only visualisation.
    out_py : Path / str
        Destination ``.py`` file.
    warp_scale : float
        Deformation magnification factor (default 10 — suitable for the
        ~100 mm tip deflection of a lightly loaded half-span model).
    show_modes : int
        Maximum number of buckling modes to display.
    span_m : float
        Half-span [m] used to position the camera.
    n_buckle_cols : int
        Number of columns in the buckling-mode small-multiple layout.

    Returns
    -------
    Path  — absolute path to the written script.
    """
    out_py = Path(out_py).resolve()
    frd_paths = [str(Path(p).resolve()) for p in frd_paths]

    static_frd = frd_paths[0] if frd_paths else None
    buckle_frds = sorted(frd_paths[1 : 1 + show_modes]) if len(frd_paths) > 1 else []

    script_name = out_py.name
    lines: List[str] = [
        _HEADER.format(script_name=script_name),
        f"SPAN_M = {span_m!r}\n\n",
    ]

    if static_frd:
        lines.append(_static_block(static_frd, warp_scale, span_m))
    else:
        lines.append("# No static result provided.\n\n")

    lines.append(_buckle_block(buckle_frds, warp_scale, span_m, n_buckle_cols))
    lines.append(_FOOTER)

    out_py.parent.mkdir(parents=True, exist_ok=True)
    out_py.write_text("".join(lines), encoding="utf-8")
    return out_py


def discover_frd_files(
    hifi_dir: Path | str,
) -> Tuple[Optional[Path], List[Path]]:
    """Scan *hifi_dir* and return (static_frd, sorted buckle_frds).

    Expected naming convention (produced by calculix_runner):
        static.frd
        buckle_mode01.frd, buckle_mode02.frd, …

    Returns ``(None, [])`` if directory does not exist or contains no .frd files.
    """
    hifi_dir = Path(hifi_dir)
    if not hifi_dir.is_dir():
        return None, []

    static_frd: Optional[Path] = None
    buckle_frds: List[Path] = []

    for frd in sorted(hifi_dir.glob("*.frd")):
        stem = frd.stem.lower()
        if stem == "static" or stem.startswith("static"):
            static_frd = frd
        elif "buckle" in stem or "mode" in stem or "eigen" in stem:
            buckle_frds.append(frd)

    buckle_frds.sort()
    return static_frd, buckle_frds
