"""Prepare and optionally run origin-VSP SU2 alpha-sweep cases."""

from __future__ import annotations

import json
import math
import re
import shutil
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Any, Sequence

from hpa_mdo.aero.origin_gmsh_mesh import generate_stl_external_flow_mesh
from hpa_mdo.aero.vsp_builder import VSPBuilder, _has_openvsp
from hpa_mdo.core.config import load_config

DEFAULT_WALL_MARKER = "aircraft"
DEFAULT_FARFIELD_MARKER = "farfield"
DEFAULT_MESH_FILENAME = "origin_mesh.su2"
DEFAULT_SU2_ITER = 1500
_CFG_VALUE_RE = re.compile(r"^\s*([^=%#]+?)\s*=\s*(.+?)\s*$")


def _format_alpha_case_name(alpha_deg: float) -> str:
    magnitude = f"{abs(float(alpha_deg)):.3f}".rstrip("0").rstrip(".")
    if "." not in magnitude:
        magnitude += ".0"
    token = magnitude.replace(".", "p")
    if float(alpha_deg) < 0.0:
        token = f"m{token}"
    return f"alpha_{token}"


def _flow_temperature_k(cfg: Any) -> float:
    temperature = getattr(getattr(cfg, "flight", None), "temperature", None)
    if temperature is None:
        altitude = float(getattr(getattr(cfg, "flight", None), "altitude", 0.0) or 0.0)
        lapse_rate = 0.0065
        return max(216.65, 288.15 - lapse_rate * altitude)
    value = float(temperature)
    if value > 170.0:
        return value
    return value + 273.15


def _resolve_origin_reference_values(cfg: Any) -> dict[str, float]:
    refs: dict[str, float] = {}
    vsp_path = Path(cfg.io.vsp_model).expanduser().resolve()
    builder = VSPBuilder(cfg)

    if _has_openvsp() and vsp_path.exists():
        try:
            import openvsp as vsp  # type: ignore

            vsp.ClearVSPModel()
            vsp.ReadVSPFile(str(vsp_path))
            vsp.Update()
            refs = builder._current_vspaero_reference_values(vsp)
        except Exception:
            refs = {}

    if refs:
        return refs

    wing = cfg.wing
    half_area = 0.5 * (float(wing.root_chord) + float(wing.tip_chord)) * float(wing.span) * 0.5
    sref = 2.0 * half_area
    return {
        "sref": sref,
        "bref": float(wing.span),
        "cref": 0.5 * (float(wing.root_chord) + float(wing.tip_chord)),
        "xcg": 0.0,
        "ycg": 0.0,
        "zcg": 0.0,
    }


def _export_origin_cfd_geometry(*, vsp3_path: str | Path, output_dir: str | Path) -> dict[str, str]:
    if not _has_openvsp():
        raise RuntimeError("openvsp python bindings are required to export origin CFD geometry")

    import openvsp as vsp  # type: ignore

    vsp_path = Path(vsp3_path).expanduser().resolve()
    out_dir = Path(output_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    exports = {
        "step": out_dir / "origin_surface.step",
        "stl": out_dir / "origin_surface.stl",
    }
    export_kinds = {
        "step": getattr(vsp, "EXPORT_STEP"),
        "stl": getattr(vsp, "EXPORT_STL"),
    }

    vsp.ClearVSPModel()
    vsp.ReadVSPFile(str(vsp_path))
    vsp.Update()
    for kind, out_path in exports.items():
        vsp.ExportFile(str(out_path), getattr(vsp, "SET_ALL", 0), export_kinds[kind])
    return {key: str(path.resolve()) for key, path in exports.items()}


def _velocity_components(velocity_mps: float, alpha_deg: float) -> tuple[float, float, float]:
    alpha_rad = math.radians(float(alpha_deg))
    return (
        float(velocity_mps * math.cos(alpha_rad)),
        0.0,
        float(velocity_mps * math.sin(alpha_rad)),
    )


def _build_su2_config_text(
    *,
    refs: dict[str, float],
    velocity_mps: float,
    density_kgpm3: float,
    temperature_k: float,
    dynamic_viscosity_pas: float,
    alpha_deg: float,
    mesh_filename: str,
    wall_marker: str,
    farfield_marker: str,
) -> str:
    vx, vy, vz = _velocity_components(velocity_mps, alpha_deg)
    lines = [
        "% Auto-generated by hpa-mdo origin_su2.py",
        f"% Alpha sweep case for alpha={alpha_deg:.6f} deg",
        "SOLVER= INC_NAVIER_STOKES",
        "KIND_TURB_MODEL= NONE",
        "MATH_PROBLEM= DIRECT",
        "SYSTEM_MEASUREMENTS= SI",
        "RESTART_SOL= NO",
        "INC_NONDIM= INITIAL_VALUES",
        "VISCOSITY_MODEL= CONSTANT_VISCOSITY",
        f"MU_CONSTANT= {dynamic_viscosity_pas:.6e}",
        f"INC_DENSITY_INIT= {density_kgpm3:.6f}",
        f"INC_TEMPERATURE_INIT= {temperature_k:.6f}",
        f"INC_VELOCITY_INIT= ( {vx:.6f}, {vy:.6f}, {vz:.6f} )",
        f"AOA= {alpha_deg:.6f}",
        "SIDESLIP_ANGLE= 0.000000",
        f"REF_AREA= {float(refs['sref']):.6f}",
        f"REF_LENGTH= {float(refs['cref']):.6f}",
        f"REF_ORIGIN_MOMENT_X= {float(refs.get('xcg', 0.0)):.6f}",
        f"REF_ORIGIN_MOMENT_Y= {float(refs.get('ycg', 0.0)):.6f}",
        f"REF_ORIGIN_MOMENT_Z= {float(refs.get('zcg', 0.0)):.6f}",
        f"MESH_FILENAME= {mesh_filename}",
        "MESH_FORMAT= SU2",
        f"MARKER_HEATFLUX= ( {wall_marker}, 0.0 )",
        f"MARKER_PLOTTING= ( {wall_marker} )",
        f"MARKER_MONITORING= ( {wall_marker} )",
        f"MARKER_FAR= ( {farfield_marker} )",
        "NUM_METHOD_GRAD= WEIGHTED_LEAST_SQUARES",
        "CONV_NUM_METHOD_FLOW= FDS",
        "TIME_DISCRE_FLOW= EULER_IMPLICIT",
        "LINEAR_SOLVER= FGMRES",
        "LINEAR_SOLVER_PREC= ILU",
        "LINEAR_SOLVER_ERROR= 1E-6",
        "LINEAR_SOLVER_ITER= 8",
        f"ITER= {DEFAULT_SU2_ITER}",
        "CFL_NUMBER= 5.0",
        "CONV_FIELD= DRAG",
        "CONV_RESIDUAL_MINVAL= -9",
        "CONV_STARTITER= 25",
        "CONV_FILENAME= history",
        "TABULAR_FORMAT= CSV",
        "SCREEN_OUTPUT= (INNER_ITER, RMS_RES, AERO_COEFF)",
        "HISTORY_OUTPUT= (ITER, RMS_RES, AERO_COEFF)",
        "OUTPUT_FILES= (RESTART_ASCII, PARAVIEW_ASCII, SURFACE_CSV)",
        "",
    ]
    return "\n".join(lines)


def _write_mesh_placeholder(
    case_dir: Path,
    *,
    mesh_filename: str,
    wall_marker: str,
    farfield_marker: str,
) -> Path:
    placeholder = case_dir / "PUT_MESH_HERE.md"
    placeholder.write_text(
        (
            "# SU2 Mesh Needed\n\n"
            f"Place an external-flow `.su2` mesh here named `{mesh_filename}`.\n\n"
            "Expected marker contract:\n"
            f"- wall marker: `{wall_marker}` for `MARKER_HEATFLUX`, `MARKER_PLOTTING`, `MARKER_MONITORING`\n"
            f"- farfield marker: `{farfield_marker}` for `MARKER_FAR`\n\n"
            "Geometry exports for meshing live in `../geometry/`.\n"
        ),
        encoding="utf-8",
    )
    return placeholder


def _copy_case_mesh(mesh_path: Path, case_dir: Path, mesh_filename: str) -> Path:
    target = case_dir / mesh_filename
    target.write_bytes(mesh_path.read_bytes())
    return target


def _read_cfg_values(config_path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in config_path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("%") or line.startswith("#"):
            continue
        match = _CFG_VALUE_RE.match(raw_line)
        if match is None:
            continue
        key, value = match.groups()
        values[key.strip().upper()] = value.strip()
    return values


def _mesh_filename_from_runtime_cfg(runtime_cfg: Path) -> str:
    return _read_cfg_values(runtime_cfg).get("MESH_FILENAME", DEFAULT_MESH_FILENAME)


def _required_markers_for_case(case_dir: Path) -> tuple[str, str]:
    metadata_path = case_dir / "case_metadata.json"
    if metadata_path.exists():
        payload = json.loads(metadata_path.read_text(encoding="utf-8"))
        return (
            str(payload.get("wall_marker", DEFAULT_WALL_MARKER)),
            str(payload.get("farfield_marker", DEFAULT_FARFIELD_MARKER)),
        )
    return DEFAULT_WALL_MARKER, DEFAULT_FARFIELD_MARKER


def validate_su2_mesh(
    mesh_path: str | Path,
    *,
    required_markers: Sequence[str] = (DEFAULT_WALL_MARKER, DEFAULT_FARFIELD_MARKER),
) -> dict[str, Any]:
    path = Path(mesh_path).expanduser().resolve()
    if not path.exists():
        raise FileNotFoundError(f"SU2 mesh not found: {path}")

    marker_names: list[str] = []
    marker_element_counts: dict[str, int] = {}
    ndime = None
    pending_marker = None

    for raw_line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("NDIME="):
            ndime = int(line.split("=", 1)[1].strip())
            continue
        if line.startswith("MARKER_TAG="):
            pending_marker = line.split("=", 1)[1].strip()
            marker_names.append(pending_marker)
            continue
        if pending_marker is not None and line.startswith("MARKER_ELEMS="):
            marker_element_counts[pending_marker] = int(line.split("=", 1)[1].strip())
            pending_marker = None

    if ndime != 3:
        raise ValueError(f"expected a 3D SU2 mesh, found NDIME={ndime!r}: {path}")

    missing_markers = [marker for marker in required_markers if marker not in marker_names]
    if missing_markers:
        raise ValueError(
            f"SU2 mesh is missing required markers {missing_markers}: {path}"
        )

    return {
        "path": str(path),
        "ndime": ndime,
        "marker_names": marker_names,
        "marker_element_counts": marker_element_counts,
        "required_markers": [str(marker) for marker in required_markers],
    }


def _resolve_su2_binary(su2_binary: str | None = None) -> str:
    candidate = su2_binary or shutil.which("SU2_CFD")
    if candidate is None:
        raise RuntimeError("SU2_CFD is not available in PATH and no su2_binary was provided")
    return candidate


def _resolve_mpi_launcher() -> str | None:
    for candidate in ("mpirun", "mpirun-mpich", "mpiexec", "mpiexec-mpich"):
        resolved = shutil.which(candidate)
        if resolved is not None:
            return resolved
    return None


def _run_prepared_case(
    *,
    case_dir: Path,
    runtime_cfg: Path,
    su2_binary: str,
    mpi_ranks: int | None,
    dry_run: bool = False,
    timeout_seconds: int | None = None,
) -> list[str]:
    if mpi_ranks is not None and mpi_ranks > 1:
        launcher = _resolve_mpi_launcher()
        if launcher is None:
            raise RuntimeError("MPI launcher not found for requested SU2 parallel run")
        command = [launcher, "-n", str(int(mpi_ranks)), su2_binary]
        if dry_run:
            command.append("-d")
        command.append(runtime_cfg.name)
    else:
        command = [su2_binary]
        if dry_run:
            command.append("-d")
        command.append(runtime_cfg.name)
    if dry_run:
        return command
    completed = subprocess.run(
        command,
        cwd=case_dir,
        check=False,
        capture_output=True,
        text=True,
        timeout=timeout_seconds,
    )
    if completed.returncode != 0:
        raise RuntimeError(
            f"SU2 execution failed in {case_dir.name}: exit={completed.returncode}\n"
            f"{completed.stderr.strip()}"
        )
    return command


def _discover_prepared_cases(sweep_dir: Path) -> list[Path]:
    cases = sorted(
        child for child in sweep_dir.iterdir() if child.is_dir() and (child / "su2_runtime.cfg").exists()
    )
    if not cases:
        raise ValueError(f"no prepared SU2 cases found under: {sweep_dir}")
    return cases


def _history_file_for_case(case_dir: Path) -> Path | None:
    for candidate in (
        case_dir / "history.csv",
        case_dir / "history.dat",
        case_dir / "conv_history.csv",
        case_dir / "conv_history.dat",
    ):
        if candidate.exists():
            return candidate
    return None


def run_prepared_origin_su2_alpha_sweep(
    sweep_dir: str | Path,
    *,
    su2_binary: str | None = None,
    mpi_ranks: int | None = None,
    dry_run: bool = False,
    timeout_seconds: int | None = None,
) -> dict[str, Any]:
    root = Path(sweep_dir).expanduser().resolve()
    if not root.exists() or not root.is_dir():
        raise FileNotFoundError(f"SU2 sweep directory not found: {root}")

    solver_binary = (su2_binary or "SU2_CFD") if dry_run else _resolve_su2_binary(su2_binary)
    cases = _discover_prepared_cases(root)
    case_results: list[dict[str, Any]] = []

    for case_dir in cases:
        runtime_cfg = case_dir / "su2_runtime.cfg"
        mesh_filename = _mesh_filename_from_runtime_cfg(runtime_cfg)
        mesh_path = case_dir / mesh_filename
        required_markers = _required_markers_for_case(case_dir)
        mesh_validation = validate_su2_mesh(mesh_path, required_markers=required_markers)

        case_result: dict[str, Any] = {
            "case_name": case_dir.name,
            "case_dir": str(case_dir),
            "runtime_cfg": str(runtime_cfg),
            "mesh_path": str(mesh_path),
            "mesh_validation": mesh_validation,
            "status": "pending",
        }

        command = _run_prepared_case(
            case_dir=case_dir,
            runtime_cfg=runtime_cfg,
            su2_binary=solver_binary,
            mpi_ranks=mpi_ranks,
            dry_run=dry_run,
            timeout_seconds=timeout_seconds,
        )
        case_result["solver_command"] = " ".join(command)
        if dry_run:
            case_result["status"] = "dry_run"
        else:
            history_path = _history_file_for_case(case_dir)
            if history_path is None:
                raise RuntimeError(f"SU2 run completed but produced no history file: {case_dir}")
            case_result["status"] = "completed"
            case_result["history_path"] = str(history_path)
        case_results.append(case_result)

    summary = {
        "generated_at": datetime.now().isoformat(),
        "sweep_dir": str(root),
        "case_count": len(case_results),
        "dry_run": bool(dry_run),
        "mpi_ranks": mpi_ranks,
        "cases": case_results,
    }
    summary_json = root / "su2_run_summary.json"
    summary_json.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    summary["summary_json"] = str(summary_json)
    return summary


def prepare_origin_su2_alpha_sweep(
    *,
    config_path: str | Path,
    output_dir: str | Path,
    aoa_list: Sequence[float],
    mesh_path: str | Path | None = None,
    auto_mesh: bool = False,
    mesh_preset: str = "baseline",
    run_cases: bool = False,
    dry_run_cases: bool = False,
    su2_binary: str | None = None,
    mpi_ranks: int | None = None,
    wall_marker: str = DEFAULT_WALL_MARKER,
    farfield_marker: str = DEFAULT_FARFIELD_MARKER,
    mesh_filename: str = DEFAULT_MESH_FILENAME,
) -> dict[str, Any]:
    if run_cases and dry_run_cases:
        raise ValueError("run_cases and dry_run_cases cannot both be true")
    if mesh_path is not None and auto_mesh:
        raise ValueError("mesh_path and auto_mesh cannot both be set")
    if mesh_path is not None and mesh_preset != "baseline":
        raise ValueError("mesh_preset is only applicable when auto_mesh=True")

    cfg = load_config(config_path)
    vsp_path = Path(cfg.io.vsp_model).expanduser().resolve()
    sweep_dir = Path(output_dir).expanduser().resolve()
    geometry_dir = sweep_dir / "geometry"
    sweep_dir.mkdir(parents=True, exist_ok=True)
    geometry = _export_origin_cfd_geometry(vsp3_path=vsp_path, output_dir=geometry_dir)
    refs = _resolve_origin_reference_values(cfg)

    velocity_mps = float(cfg.flight.velocity)
    density_kgpm3 = float(cfg.flight.air_density)
    temperature_k = _flow_temperature_k(cfg)
    kinematic_viscosity = float(getattr(cfg.flight, "kinematic_viscosity", 1.46e-5) or 1.46e-5)
    dynamic_viscosity_pas = density_kgpm3 * kinematic_viscosity

    generated_mesh = None
    applied_mesh_preset = mesh_preset if auto_mesh else None
    mesh_source = None if mesh_path is None else Path(mesh_path).expanduser().resolve()
    if mesh_source is None and auto_mesh:
        generated_mesh_path = geometry_dir / mesh_filename
        generated_mesh = generate_stl_external_flow_mesh(
            geometry["stl"],
            generated_mesh_path,
            preset_name=mesh_preset,
            body_marker=wall_marker,
            farfield_marker=farfield_marker,
        )
        mesh_source = Path(generated_mesh["MeshFile"]).expanduser().resolve()
    if mesh_source is not None and not mesh_source.exists():
        raise FileNotFoundError(f"SU2 mesh not found: {mesh_source}")

    cases: list[dict[str, Any]] = []
    for alpha_deg in aoa_list:
        alpha_value = float(alpha_deg)
        case_name = _format_alpha_case_name(alpha_value)
        case_dir = sweep_dir / case_name
        case_dir.mkdir(parents=True, exist_ok=True)

        cfg_text = _build_su2_config_text(
            refs=refs,
            velocity_mps=velocity_mps,
            density_kgpm3=density_kgpm3,
            temperature_k=temperature_k,
            dynamic_viscosity_pas=dynamic_viscosity_pas,
            alpha_deg=alpha_value,
            mesh_filename=mesh_filename,
            wall_marker=wall_marker,
            farfield_marker=farfield_marker,
        )
        su2_case_cfg = case_dir / "su2_case.cfg"
        su2_runtime_cfg = case_dir / "su2_runtime.cfg"
        su2_case_cfg.write_text(cfg_text, encoding="utf-8")
        su2_runtime_cfg.write_text(cfg_text, encoding="utf-8")

        mesh_target = None
        mesh_validation = None
        if mesh_source is None:
            _write_mesh_placeholder(
                case_dir,
                mesh_filename=mesh_filename,
                wall_marker=wall_marker,
                farfield_marker=farfield_marker,
            )
        else:
            mesh_target = _copy_case_mesh(mesh_source, case_dir, mesh_filename)
            mesh_validation = validate_su2_mesh(
                mesh_target,
                required_markers=(wall_marker, farfield_marker),
            )

        metadata = {
            "alpha_deg": alpha_value,
            "case_name": case_name,
            "case_dir": str(case_dir),
            "mesh_filename": mesh_filename,
            "mesh_path": None if mesh_target is None else str(mesh_target),
            "mesh_validation": mesh_validation,
            "wall_marker": wall_marker,
            "farfield_marker": farfield_marker,
            "mesh_preset": applied_mesh_preset,
            "reference_values": refs,
            "geometry": geometry,
        }
        (case_dir / "case_metadata.json").write_text(
            json.dumps(metadata, indent=2) + "\n",
            encoding="utf-8",
        )

        cases.append(
            {
                "alpha_deg": alpha_value,
                "case_name": case_name,
                "case_dir": str(case_dir),
                "su2_case_cfg": str(su2_case_cfg),
                "su2_runtime_cfg": str(su2_runtime_cfg),
                "mesh_path": None if mesh_target is None else str(mesh_target),
                "mesh_validation": mesh_validation,
                "mesh_preset": applied_mesh_preset,
            }
        )

    result = {
        "generated_at": datetime.now().isoformat(),
        "config_path": str(Path(config_path).expanduser().resolve()),
        "origin_vsp_path": str(vsp_path),
        "sweep_dir": str(sweep_dir),
        "geometry": geometry,
        "reference_values": refs,
        "case_count": len(cases),
        "cases": cases,
        "mesh_path": None if mesh_source is None else str(mesh_source),
        "generated_mesh": generated_mesh,
        "mesh_preset": applied_mesh_preset,
        "run_cases": bool(run_cases),
        "dry_run_cases": bool(dry_run_cases),
        "mpi_ranks": mpi_ranks,
    }
    if run_cases or dry_run_cases:
        if mesh_source is None:
            raise RuntimeError("run_cases/dry_run_cases require mesh_path so each case has a runnable mesh")
        result["run_summary"] = run_prepared_origin_su2_alpha_sweep(
            sweep_dir,
            su2_binary=su2_binary,
            mpi_ranks=mpi_ranks,
            dry_run=dry_run_cases,
        )
    (sweep_dir / "su2_case_bundle.json").write_text(
        json.dumps(result, indent=2) + "\n",
        encoding="utf-8",
    )
    return result
