from __future__ import annotations

import json
import math
import re
import shutil
import subprocess
import tempfile
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from ..gmsh_runtime import GmshRuntimeError, load_gmsh
from ..schema import GeometryTopologyMetadata
from ..reference_geometry import load_openvsp_reference_data
from .openvsp_surface_intersection import _probe_step_topology, _read_step_units_and_bounds

Runner = Callable[[List[str], Path], subprocess.CompletedProcess]

OCSM_SCRIPT_NAME = "rebuild.csm"
UNION_SCRIPT_NAME = "union_groups.csm"
RAW_EXPORT_FILE_NAME = "raw_dump.stp"
EXPORT_FILE_NAME = "normalized.stp"
UNION_EXPORT_FILE_NAME = "union_groups.step"
COMMAND_LOG_NAME = "ocsm.log"
UNION_COMMAND_LOG_NAME = "ocsm_union.log"
TOPOLOGY_REPORT_NAME = "topology.json"
RAW_TOPOLOGY_REPORT_NAME = "raw_topology.json"
NORMALIZATION_REPORT_NAME = "normalization.json"
_STEP_MILLI_UNIT_PATTERN = re.compile(r"SI_UNIT\(\s*\.MILLI\.\s*,\s*\.METRE\.\s*\)")
_STEP_COORDS_LOOK_LIKE_METERS_MAX_REF_RATIO = 500.0
_IMPORT_SCALE_IDENTITY_TOL = 1.0e-6


@dataclass(frozen=True)
class _InterfaceFaceRecord:
    body_tag: int
    face_tag: int
    axis: str
    plane_coordinate: float
    area: float
    bbox: tuple[float, float, float, float, float, float]
    projected_bounds: tuple[float, float, float, float]
    center_of_mass: tuple[float, float, float]


@dataclass(frozen=True)
class _BodyRecord:
    body_tag: int
    bbox: tuple[float, float, float, float, float, float]
    center_of_mass: tuple[float, float, float]
    face_count: int


@dataclass(frozen=True)
class _SymmetryTouchingAnalysis:
    body_count: int
    surface_count: int
    volume_count: int
    body_records: list[_BodyRecord]
    duplicate_face_pairs: list[dict[str, Any]]
    touching_groups: list[dict[str, Any]]
    singleton_body_tags: list[int]
    grouped_body_tags: list[int]
    internal_cap_face_tags: list[int]
    notes: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class EspMaterializationResult:
    status: str
    normalized_geometry_path: Optional[Path]
    topology_report_path: Optional[Path]
    topology: Optional[GeometryTopologyMetadata] = None
    notes: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    failure_code: Optional[str] = None
    provider_version: Optional[str] = None
    command_log_path: Optional[Path] = None
    script_path: Optional[Path] = None
    input_model_path: Optional[Path] = None
    provenance: Dict[str, Any] = field(default_factory=dict)
    artifacts: Dict[str, Path] = field(default_factory=dict)


def _default_runner(args: List[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        args,
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=False,
    )


def _resolve_batch_binary() -> Optional[str]:
    for candidate in ("serveCSM", "ocsm"):
        resolved = shutil.which(candidate)
        if resolved is not None:
            return resolved
    return None


def _build_csm_script(source_path: Path, export_path: Path) -> str:
    script_lines = [
        "# Auto-generated by hpa_meshing.providers.esp_pipeline",
        "# Rebuilds OpenVSP model through the official UDPRIM vsp3 bridge",
        f"SET vsp_model_path $\"{source_path}\"",
        f"SET export_path $\"{export_path}\"",
        "UDPRIM vsp3 filename !vsp_model_path",
        "STORE aircraft_assembly",
        "RESTORE aircraft_assembly",
        "DUMP !export_path 0 1",
        "END",
        "",
    ]
    return "\n".join(script_lines)


def _build_union_csm_script(source_path: Path, export_path: Path, body_count: int) -> str:
    script_lines = [
        "# Auto-generated by hpa_meshing.providers.esp_pipeline",
        "# Unions touching ESP/OpenCSM bodies produced by the UDPRIM vsp3 bridge",
        f"SET vsp_model_path $\"{source_path}\"",
        f"SET export_path $\"{export_path}\"",
        "UDPRIM vsp3 filename !vsp_model_path",
        f"UNION {body_count}",
        "DUMP !export_path 0 1",
        "END",
        "",
    ]
    return "\n".join(script_lines)


def _bbox_close(lhs: tuple[float, ...], rhs: tuple[float, ...], tol: float) -> bool:
    return all(abs(float(a) - float(b)) <= tol for a, b in zip(lhs, rhs))


def _body_is_mirrored_across_plane(
    lhs: _BodyRecord,
    rhs: _BodyRecord,
    *,
    axis_index: int,
    plane_coordinate: float,
    tol: float,
) -> bool:
    lhs_bbox = lhs.bbox
    rhs_bbox = rhs.bbox
    lhs_min = lhs_bbox[axis_index]
    lhs_max = lhs_bbox[axis_index + 3]
    rhs_min = rhs_bbox[axis_index]
    rhs_max = rhs_bbox[axis_index + 3]
    lhs_dist = max(abs(lhs_min - plane_coordinate), abs(lhs_max - plane_coordinate))
    rhs_dist = max(abs(rhs_min - plane_coordinate), abs(rhs_max - plane_coordinate))
    if abs(lhs_dist - rhs_dist) > tol:
        return False

    if not (
        (abs(lhs_min - plane_coordinate) <= tol and abs(rhs_max - plane_coordinate) <= tol)
        or (abs(lhs_max - plane_coordinate) <= tol and abs(rhs_min - plane_coordinate) <= tol)
    ):
        return False

    for offset in (0, 1, 2):
        if offset == axis_index:
            continue
        if abs(lhs_bbox[offset] - rhs_bbox[offset]) > tol:
            return False
        if abs(lhs_bbox[offset + 3] - rhs_bbox[offset + 3]) > tol:
            return False

    lhs_com = lhs.center_of_mass[axis_index]
    rhs_com = rhs.center_of_mass[axis_index]
    if abs(((lhs_com + rhs_com) / 2.0) - plane_coordinate) > tol:
        return False

    return True


def _write_normalization_report(path: Path, payload: Dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def _analyze_symmetry_touching_solids(step_path: Path) -> _SymmetryTouchingAnalysis:
    try:
        gmsh = load_gmsh()
    except GmshRuntimeError:
        return _SymmetryTouchingAnalysis(
            body_count=0,
            surface_count=0,
            volume_count=0,
            body_records=[],
            duplicate_face_pairs=[],
            touching_groups=[],
            singleton_body_tags=[],
            grouped_body_tags=[],
            internal_cap_face_tags=[],
            notes=["gmsh_python_api_not_available_for_symmetry_touching_analysis"],
        )

    gmsh_initialized = False
    try:
        gmsh.initialize()
        gmsh_initialized = True
        gmsh.option.setNumber("General.Terminal", 0)
        gmsh.model.add(f"esp_symmetry_probe_{next(tempfile._get_candidate_names())}")
        imported_entities = gmsh.model.occ.importShapes(str(step_path))
        gmsh.model.occ.synchronize()
        body_dim_tags = [entity for entity in imported_entities if entity[0] == 3]
        if not body_dim_tags:
            body_dim_tags = gmsh.model.getEntities(3)
        surface_count = len(gmsh.model.getEntities(2))
        if not body_dim_tags:
            return _SymmetryTouchingAnalysis(
                body_count=0,
                surface_count=surface_count,
                volume_count=0,
                body_records=[],
                duplicate_face_pairs=[],
                touching_groups=[],
                singleton_body_tags=[],
                grouped_body_tags=[],
                internal_cap_face_tags=[],
                notes=["step_import_contains_no_occ_volumes"],
            )

        model_bbox = [float("inf"), float("inf"), float("inf"), float("-inf"), float("-inf"), float("-inf")]
        body_records: dict[int, _BodyRecord] = {}
        planar_faces_by_body: dict[int, list[_InterfaceFaceRecord]] = defaultdict(list)
        for _, body_tag in body_dim_tags:
            bbox = tuple(float(value) for value in gmsh.model.getBoundingBox(3, body_tag))
            model_bbox[0] = min(model_bbox[0], bbox[0])
            model_bbox[1] = min(model_bbox[1], bbox[1])
            model_bbox[2] = min(model_bbox[2], bbox[2])
            model_bbox[3] = max(model_bbox[3], bbox[3])
            model_bbox[4] = max(model_bbox[4], bbox[4])
            model_bbox[5] = max(model_bbox[5], bbox[5])
            body_boundary = gmsh.model.getBoundary([(3, body_tag)], oriented=False, recursive=False)
            face_tags = [int(tag) for dim, tag in body_boundary if dim == 2]
            body_records[body_tag] = _BodyRecord(
                body_tag=body_tag,
                bbox=bbox,
                center_of_mass=tuple(float(value) for value in gmsh.model.occ.getCenterOfMass(3, body_tag)),
                face_count=len(face_tags),
            )
            for face_tag in face_tags:
                face_bbox = tuple(float(value) for value in gmsh.model.getBoundingBox(2, face_tag))
                spans = (
                    face_bbox[3] - face_bbox[0],
                    face_bbox[4] - face_bbox[1],
                    face_bbox[5] - face_bbox[2],
                )
                axis_index = min(range(3), key=spans.__getitem__)
                global_span = max(
                    model_bbox[3] - model_bbox[0],
                    model_bbox[4] - model_bbox[1],
                    model_bbox[5] - model_bbox[2],
                    1.0,
                )
                plane_tol = global_span * 1.0e-7
                if spans[axis_index] > plane_tol:
                    continue
                other_axes = [index for index in range(3) if index != axis_index]
                projected_bounds = (
                    face_bbox[other_axes[0]],
                    face_bbox[other_axes[0] + 3],
                    face_bbox[other_axes[1]],
                    face_bbox[other_axes[1] + 3],
                )
                planar_faces_by_body[body_tag].append(
                    _InterfaceFaceRecord(
                        body_tag=body_tag,
                        face_tag=face_tag,
                        axis="xyz"[axis_index],
                        plane_coordinate=0.5 * (face_bbox[axis_index] + face_bbox[axis_index + 3]),
                        area=float(gmsh.model.occ.getMass(2, face_tag)),
                        bbox=face_bbox,
                        projected_bounds=projected_bounds,
                        center_of_mass=tuple(
                            float(value) for value in gmsh.model.occ.getCenterOfMass(2, face_tag)
                        ),
                    )
                )

        global_span = max(
            model_bbox[3] - model_bbox[0],
            model_bbox[4] - model_bbox[1],
            model_bbox[5] - model_bbox[2],
            1.0,
        )
        plane_tol = global_span * 1.0e-7
        bbox_tol = global_span * 2.0e-6
        area_tol = max(global_span * global_span * 1.0e-8, 1.0e-12)

        duplicate_face_pairs: list[dict[str, Any]] = []
        group_evidence: list[dict[str, Any]] = []
        edge_map: dict[int, set[int]] = defaultdict(set)
        body_tags = sorted(body_records)
        for index, lhs_body in enumerate(body_tags):
            lhs_record = body_records[lhs_body]
            lhs_faces = planar_faces_by_body.get(lhs_body, [])
            if not lhs_faces:
                continue
            for rhs_body in body_tags[index + 1:]:
                rhs_record = body_records[rhs_body]
                rhs_faces = planar_faces_by_body.get(rhs_body, [])
                if not rhs_faces:
                    continue
                exact_pairs: list[dict[str, Any]] = []
                for lhs_face in lhs_faces:
                    for rhs_face in rhs_faces:
                        if lhs_face.axis != rhs_face.axis:
                            continue
                        if abs(lhs_face.plane_coordinate - rhs_face.plane_coordinate) > plane_tol:
                            continue
                        if not _bbox_close(lhs_face.projected_bounds, rhs_face.projected_bounds, bbox_tol):
                            continue
                        if abs(lhs_face.area - rhs_face.area) > max(area_tol, abs(lhs_face.area) * 1.0e-6):
                            continue
                        exact_pairs.append(
                            {
                                "body_tags": [lhs_body, rhs_body],
                                "face_tags": [lhs_face.face_tag, rhs_face.face_tag],
                                "axis": lhs_face.axis,
                                "plane_coordinate": lhs_face.plane_coordinate,
                                "area": lhs_face.area,
                                "projected_bounds": list(lhs_face.projected_bounds),
                                "bbox_lhs": list(lhs_face.bbox),
                                "bbox_rhs": list(rhs_face.bbox),
                            }
                        )
                if exact_pairs:
                    plane_coordinate = float(
                        sum(pair["plane_coordinate"] for pair in exact_pairs) / len(exact_pairs)
                    )
                    axis_index = "xyz".index(exact_pairs[0]["axis"])
                    if _body_is_mirrored_across_plane(
                        lhs_record,
                        rhs_record,
                        axis_index=axis_index,
                        plane_coordinate=plane_coordinate,
                        tol=bbox_tol,
                    ):
                        duplicate_face_pairs.extend(exact_pairs)
                        group_evidence.append(
                            {
                                "body_tags": [lhs_body, rhs_body],
                                "axis": exact_pairs[0]["axis"],
                                "plane_coordinate": plane_coordinate,
                                "match_kind": "exact_duplicate_faces",
                                "duplicate_face_pairs": len(exact_pairs),
                                "interface_area": sum(pair["area"] for pair in exact_pairs),
                            }
                        )
                        edge_map[lhs_body].add(rhs_body)
                        edge_map[rhs_body].add(lhs_body)
                        continue

                for axis in "xyz":
                    lhs_axis_faces = [face for face in lhs_faces if face.axis == axis]
                    rhs_axis_faces = [face for face in rhs_faces if face.axis == axis]
                    if not lhs_axis_faces or not rhs_axis_faces:
                        continue

                    def _cluster_by_plane_coordinate(
                        faces: list[_InterfaceFaceRecord],
                    ) -> list[list[_InterfaceFaceRecord]]:
                        clusters: list[list[_InterfaceFaceRecord]] = []
                        for face in sorted(faces, key=lambda item: item.plane_coordinate):
                            if not clusters:
                                clusters.append([face])
                                continue
                            cluster_coord = sum(
                                member.plane_coordinate for member in clusters[-1]
                            ) / len(clusters[-1])
                            if abs(face.plane_coordinate - cluster_coord) <= plane_tol:
                                clusters[-1].append(face)
                            else:
                                clusters.append([face])
                        return clusters

                    lhs_clusters = _cluster_by_plane_coordinate(lhs_axis_faces)
                    rhs_clusters = _cluster_by_plane_coordinate(rhs_axis_faces)
                    matched_cluster = False
                    for lhs_cluster in lhs_clusters:
                        lhs_coord = sum(face.plane_coordinate for face in lhs_cluster) / len(lhs_cluster)
                        lhs_projected = (
                            min(face.projected_bounds[0] for face in lhs_cluster),
                            max(face.projected_bounds[1] for face in lhs_cluster),
                            min(face.projected_bounds[2] for face in lhs_cluster),
                            max(face.projected_bounds[3] for face in lhs_cluster),
                        )
                        lhs_area = sum(face.area for face in lhs_cluster)
                        for rhs_cluster in rhs_clusters:
                            rhs_coord = sum(face.plane_coordinate for face in rhs_cluster) / len(rhs_cluster)
                            if abs(lhs_coord - rhs_coord) > plane_tol:
                                continue
                            rhs_projected = (
                                min(face.projected_bounds[0] for face in rhs_cluster),
                                max(face.projected_bounds[1] for face in rhs_cluster),
                                min(face.projected_bounds[2] for face in rhs_cluster),
                                max(face.projected_bounds[3] for face in rhs_cluster),
                            )
                            if not _bbox_close(lhs_projected, rhs_projected, bbox_tol):
                                continue
                            rhs_area = sum(face.area for face in rhs_cluster)
                            if abs(lhs_area - rhs_area) > max(area_tol, max(lhs_area, rhs_area) * 1.0e-6):
                                continue
                            axis_index = "xyz".index(axis)
                            plane_coordinate = 0.5 * (lhs_coord + rhs_coord)
                            if not _body_is_mirrored_across_plane(
                                lhs_record,
                                rhs_record,
                                axis_index=axis_index,
                                plane_coordinate=plane_coordinate,
                                tol=bbox_tol,
                            ):
                                continue
                            group_evidence.append(
                                {
                                    "body_tags": [lhs_body, rhs_body],
                                    "axis": axis,
                                    "plane_coordinate": plane_coordinate,
                                    "match_kind": "aggregate_planar_interface",
                                    "duplicate_face_pairs": 0,
                                    "interface_area": min(lhs_area, rhs_area),
                                    "lhs_face_tags": [face.face_tag for face in lhs_cluster],
                                    "rhs_face_tags": [face.face_tag for face in rhs_cluster],
                                }
                            )
                            edge_map[lhs_body].add(rhs_body)
                            edge_map[rhs_body].add(lhs_body)
                            matched_cluster = True
                            break
                        if matched_cluster:
                            break
                    if matched_cluster:
                        break

        visited: set[int] = set()
        touching_groups: list[dict[str, Any]] = []
        grouped_body_tags: list[int] = []
        for body_tag in body_tags:
            if body_tag in visited or not edge_map.get(body_tag):
                continue
            component: list[int] = []
            stack = [body_tag]
            while stack:
                current = stack.pop()
                if current in visited:
                    continue
                visited.add(current)
                component.append(current)
                stack.extend(sorted(edge_map.get(current, set()) - visited))
            component.sort()
            grouped_body_tags.extend(component)
            evidence = [
                item
                for item in group_evidence
                if set(item["body_tags"]).issubset(component)
            ]
            planes = [
                {
                    "axis": item["axis"],
                    "plane_coordinate": item["plane_coordinate"],
                    "match_kind": item["match_kind"],
                    "interface_area": item["interface_area"],
                    "duplicate_face_pairs": item["duplicate_face_pairs"],
                }
                for item in evidence
            ]
            touching_groups.append(
                {
                    "body_tags": component,
                    "plane_count": len(planes),
                    "planes": planes,
                }
            )

        grouped_body_tag_set = set(grouped_body_tags)
        singleton_body_tags = [tag for tag in body_tags if tag not in grouped_body_tag_set]
        internal_cap_face_tags = sorted(
            {
                face_tag
                for pair in duplicate_face_pairs
                for face_tag in pair["face_tags"]
            }
        )

        return _SymmetryTouchingAnalysis(
            body_count=len(body_dim_tags),
            surface_count=surface_count,
            volume_count=len(body_dim_tags),
            body_records=[body_records[tag] for tag in body_tags],
            duplicate_face_pairs=duplicate_face_pairs,
            touching_groups=touching_groups,
            singleton_body_tags=singleton_body_tags,
            grouped_body_tags=sorted(grouped_body_tag_set),
            internal_cap_face_tags=internal_cap_face_tags,
            notes=[],
        )
    except Exception as exc:
        return _SymmetryTouchingAnalysis(
            body_count=0,
            surface_count=0,
            volume_count=0,
            body_records=[],
            duplicate_face_pairs=[],
            touching_groups=[],
            singleton_body_tags=[],
            grouped_body_tags=[],
            internal_cap_face_tags=[],
            notes=[f"symmetry_touching_analysis_error={exc}"],
        )
    finally:
        if gmsh_initialized:
            gmsh.finalize()


def _apply_import_scale_if_needed(gmsh, entities: list[tuple[int, int]], import_scale: float | None) -> None:
    if import_scale is None:
        return
    if abs(float(import_scale) - 1.0) <= _IMPORT_SCALE_IDENTITY_TOL:
        return
    gmsh.model.occ.dilate(
        entities,
        0.0,
        0.0,
        0.0,
        float(import_scale),
        float(import_scale),
        float(import_scale),
    )
    gmsh.model.occ.synchronize()


def _combine_union_groups_with_singletons(
    *,
    raw_step_path: Path,
    raw_topology: GeometryTopologyMetadata,
    singleton_body_tags: list[int],
    union_step_path: Path,
    union_topology: GeometryTopologyMetadata,
    output_path: Path,
) -> None:
    gmsh = load_gmsh()
    gmsh_initialized = False
    try:
        gmsh.initialize()
        gmsh_initialized = True
        gmsh.option.setNumber("General.Terminal", 0)
        gmsh.model.add(f"esp_normalize_{next(tempfile._get_candidate_names())}")
        raw_entities = gmsh.model.occ.importShapes(str(raw_step_path))
        gmsh.model.occ.synchronize()
        _apply_import_scale_if_needed(gmsh, raw_entities, raw_topology.import_scale_to_units)
        raw_volume_tags = [tag for dim, tag in gmsh.model.getEntities(3) if dim == 3]
        remove_entities = [(3, tag) for tag in raw_volume_tags if tag not in set(singleton_body_tags)]
        if remove_entities:
            gmsh.model.occ.remove(remove_entities, recursive=True)
            gmsh.model.occ.synchronize()
        union_entities = gmsh.model.occ.importShapes(str(union_step_path))
        gmsh.model.occ.synchronize()
        _apply_import_scale_if_needed(gmsh, union_entities, union_topology.import_scale_to_units)
        gmsh.write(str(output_path))
    finally:
        if gmsh_initialized:
            gmsh.finalize()


def _prepare_runtime_dirs(staging_dir: Path) -> tuple[Path, Path]:
    artifact_dir = (staging_dir / "esp_runtime").resolve()
    artifact_dir.mkdir(parents=True, exist_ok=True)
    scratch_root = Path(
        tempfile.mkdtemp(prefix="hpa_esp_runtime_", dir="/tmp")
    ).resolve()
    work_dir = scratch_root / "runtime"
    work_dir.symlink_to(artifact_dir, target_is_directory=True)
    return artifact_dir, work_dir


def _stage_source_model(
    source_path: Path,
    artifact_dir: Path,
    work_dir: Path,
) -> tuple[Path, Path]:
    resolved_source = source_path.resolve()
    artifact_source = (artifact_dir / resolved_source.name).resolve()
    if artifact_source != resolved_source:
        shutil.copy2(resolved_source, artifact_source)
    work_source = work_dir / artifact_source.name
    return artifact_source, work_source


def _write_topology_report(
    *,
    report_path: Path,
    export_path: Path,
    source_path: Path,
    input_model_path: Path,
    batch_binary: str,
    runtime_exec_dir: Path,
    stdout: str,
    stderr: str,
    extra_notes: Optional[List[str]] = None,
    extra_payload: Optional[Dict[str, Any]] = None,
) -> GeometryTopologyMetadata:
    topology = _probe_step_topology(export_path, report_path.parent)
    for note in extra_notes or []:
        if note not in topology.notes:
            topology.notes.append(note)
    payload: Dict[str, Any] = topology.model_dump(mode="json")
    payload.update(
        {
        "source_path": str(source_path),
        "input_model_path": str(input_model_path),
        "export_path": str(export_path),
        "export_exists": export_path.exists(),
        "export_size_bytes": export_path.stat().st_size if export_path.exists() else None,
        "batch_binary": batch_binary,
        "runtime_exec_dir": str(runtime_exec_dir),
        "stdout_tail": stdout[-2000:] if stdout else "",
        "stderr_tail": stderr[-2000:] if stderr else "",
        }
    )
    if extra_payload:
        payload.update(extra_payload)
    report_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return topology


def _rewrite_mislabeled_mm_step_to_meters_if_needed(
    *,
    export_path: Path,
    source_path: Path,
) -> List[str]:
    declared_units, bounds = _read_step_units_and_bounds(export_path)
    if declared_units != "mm" or bounds is None:
        return []

    reference_data = load_openvsp_reference_data(source_path)
    ref_length = None if reference_data is None else reference_data.get("ref_length")
    if not isinstance(ref_length, (int, float)) or float(ref_length) <= 0.0:
        return []

    max_span = max(
        bounds.x_max - bounds.x_min,
        bounds.y_max - bounds.y_min,
        bounds.z_max - bounds.z_min,
    )
    if max_span <= 0.0:
        return []

    # For aircraft assemblies, meter-scale coordinates should stay O(1..100) times the
    # reference chord. If the STEP says "mm" but the coordinates are still in this
    # range, ESP likely mislabeled the units rather than scaling the geometry.
    if (max_span / float(ref_length)) >= _STEP_COORDS_LOOK_LIKE_METERS_MAX_REF_RATIO:
        return []

    original_text = export_path.read_text(encoding="utf-8", errors="ignore")
    rewritten_text, replacements = _STEP_MILLI_UNIT_PATTERN.subn(
        "SI_UNIT(.UNSET.,.METRE.)",
        original_text,
    )
    if replacements == 0:
        return []

    export_path.write_text(rewritten_text, encoding="utf-8")
    return [
        "rewrote_step_length_units:mm_to_m_based_on_reference_length"
        f":ref_length={float(ref_length):.12g}:max_span={max_span:.12g}"
    ]


def _write_command_log(
    *,
    log_path: Path,
    args: List[str],
    returncode: int,
    stdout: str,
    stderr: str,
) -> None:
    log_path.write_text(
        "\n".join(
            [
                "command: " + " ".join(args),
                f"returncode: {returncode}",
                "--- stdout ---",
                stdout,
                "--- stderr ---",
                stderr,
                "",
            ]
        ),
        encoding="utf-8",
    )


def _run_ocsm_batch(
    *,
    runner: Runner,
    batch_binary: str,
    work_dir: Path,
    script_path: Path,
    command_log_path: Path,
) -> subprocess.CompletedProcess:
    args = [batch_binary, "-batch", str(script_path)]
    completed = runner(args, work_dir)
    _write_command_log(
        log_path=command_log_path,
        args=args,
        returncode=completed.returncode,
        stdout=completed.stdout or "",
        stderr=completed.stderr or "",
    )
    return completed


def materialize_with_esp(
    *,
    source_path: Path,
    staging_dir: Path,
    runner: Optional[Runner] = None,
    batch_binary: Optional[str] = None,
) -> EspMaterializationResult:
    artifact_dir, work_dir = _prepare_runtime_dirs(staging_dir)

    source_path = source_path.resolve()
    artifact_source_path, work_source_path = _stage_source_model(
        source_path,
        artifact_dir,
        work_dir,
    )
    script_path = (artifact_dir / OCSM_SCRIPT_NAME).resolve()
    union_script_path = (artifact_dir / UNION_SCRIPT_NAME).resolve()
    raw_export_path = (artifact_dir / RAW_EXPORT_FILE_NAME).resolve()
    export_path = (artifact_dir / EXPORT_FILE_NAME).resolve()
    union_export_path = (artifact_dir / UNION_EXPORT_FILE_NAME).resolve()
    command_log_path = (artifact_dir / COMMAND_LOG_NAME).resolve()
    union_command_log_path = (artifact_dir / UNION_COMMAND_LOG_NAME).resolve()
    topology_report_path = (artifact_dir / TOPOLOGY_REPORT_NAME).resolve()
    raw_topology_report_path = (artifact_dir / RAW_TOPOLOGY_REPORT_NAME).resolve()
    normalization_report_path = (artifact_dir / NORMALIZATION_REPORT_NAME).resolve()
    work_script_path = work_dir / OCSM_SCRIPT_NAME
    work_union_script_path = work_dir / UNION_SCRIPT_NAME
    work_raw_export_path = work_dir / RAW_EXPORT_FILE_NAME
    work_export_path = work_dir / EXPORT_FILE_NAME
    work_union_export_path = work_dir / UNION_EXPORT_FILE_NAME

    script_path.write_text(
        _build_csm_script(source_path=work_source_path, export_path=work_raw_export_path),
        encoding="utf-8",
    )

    resolved_runner = runner or _default_runner
    resolved_binary = batch_binary or _resolve_batch_binary()
    if resolved_binary is None:
        reason = "Neither serveCSM nor ocsm was resolvable on PATH."
        _write_command_log(
            log_path=command_log_path,
            args=[],
            returncode=-1,
            stdout="",
            stderr=reason,
        )
        return EspMaterializationResult(
            status="failed",
            normalized_geometry_path=None,
            topology_report_path=None,
            notes=[reason],
            warnings=[reason],
            failure_code="esp_batch_binary_missing",
            command_log_path=command_log_path,
            script_path=script_path,
            input_model_path=artifact_source_path,
            artifacts={
                "esp_script": script_path,
                "esp_input_model": artifact_source_path,
            },
        )

    completed = _run_ocsm_batch(
        runner=resolved_runner,
        batch_binary=resolved_binary,
        work_dir=work_dir,
        script_path=work_script_path,
        command_log_path=command_log_path,
    )

    if completed.returncode != 0:
        reason = (
            f"OpenCSM batch exited with status {completed.returncode}. "
            "Inspect the command log for serveCSM/ocsm diagnostics."
        )
        return EspMaterializationResult(
            status="failed",
            normalized_geometry_path=None,
            topology_report_path=None,
            notes=[reason],
            warnings=[reason],
            failure_code="esp_ocsm_batch_failed",
            command_log_path=command_log_path,
            script_path=script_path,
            input_model_path=artifact_source_path,
            artifacts={
                "esp_script": script_path,
                "esp_input_model": artifact_source_path,
                "command_log": command_log_path,
            },
        )

    if not raw_export_path.exists():
        reason = (
            "OpenCSM batch returned success but did not emit the expected normalized "
            f"STEP export at {raw_export_path}."
        )
        return EspMaterializationResult(
            status="failed",
            normalized_geometry_path=None,
            topology_report_path=None,
            notes=[reason],
            warnings=[reason],
            failure_code="esp_export_missing",
            command_log_path=command_log_path,
            script_path=script_path,
            input_model_path=artifact_source_path,
            artifacts={
                "esp_script": script_path,
                "esp_input_model": artifact_source_path,
                "command_log": command_log_path,
            },
        )

    raw_unit_notes = _rewrite_mislabeled_mm_step_to_meters_if_needed(
        export_path=raw_export_path,
        source_path=source_path,
    )
    raw_topology = _write_topology_report(
        report_path=raw_topology_report_path,
        export_path=raw_export_path,
        source_path=source_path,
        input_model_path=artifact_source_path,
        batch_binary=resolved_binary,
        runtime_exec_dir=work_dir,
        stdout=completed.stdout or "",
        stderr=completed.stderr or "",
        extra_notes=raw_unit_notes,
    )
    raw_analysis = _analyze_symmetry_touching_solids(raw_export_path)

    normalization_payload: Dict[str, Any] = {
        "strategy": "ocsm_union_touching_groups_plus_occ_singletons",
        "applied": False,
        "raw_counts": {
            "body_count": raw_topology.body_count,
            "surface_count": raw_topology.surface_count,
            "volume_count": raw_topology.volume_count,
        },
        "raw_analysis": {
            "touching_groups": raw_analysis.touching_groups,
            "singleton_body_tags": raw_analysis.singleton_body_tags,
            "grouped_body_tags": raw_analysis.grouped_body_tags,
            "duplicate_interface_face_pair_count": len(raw_analysis.duplicate_face_pairs),
            "duplicate_interface_face_pairs": raw_analysis.duplicate_face_pairs,
            "internal_cap_face_count": len(raw_analysis.internal_cap_face_tags),
            "internal_cap_face_tags": raw_analysis.internal_cap_face_tags,
            "body_records": [
                {
                    "body_tag": record.body_tag,
                    "bbox": list(record.bbox),
                    "center_of_mass": list(record.center_of_mass),
                    "face_count": record.face_count,
                }
                for record in raw_analysis.body_records
            ],
            "notes": raw_analysis.notes,
        },
        "actions": [],
    }

    final_notes = list(raw_unit_notes)
    final_warnings: list[str] = []
    final_stdout = completed.stdout or ""
    final_stderr = completed.stderr or ""
    output_artifacts: Dict[str, Path] = {
        "esp_script": script_path,
        "esp_input_model": artifact_source_path,
        "command_log": command_log_path,
        "raw_geometry": raw_export_path,
        "raw_topology_report": raw_topology_report_path,
        "normalization_report": normalization_report_path,
    }

    if raw_analysis.touching_groups:
        union_script_path.write_text(
            _build_union_csm_script(
                source_path=work_source_path,
                export_path=work_union_export_path,
                body_count=max(raw_analysis.body_count, 1),
            ),
            encoding="utf-8",
        )
        union_completed = _run_ocsm_batch(
            runner=resolved_runner,
            batch_binary=resolved_binary,
            work_dir=work_dir,
            script_path=work_union_script_path,
            command_log_path=union_command_log_path,
        )
        output_artifacts.update(
            {
                "union_geometry": union_export_path,
                "union_command_log": union_command_log_path,
                "union_script": union_script_path,
            }
        )
        if union_completed.returncode != 0:
            reason = (
                f"OpenCSM union normalization batch exited with status {union_completed.returncode}. "
                "Inspect the union command log for diagnostics."
            )
            return EspMaterializationResult(
                status="failed",
                normalized_geometry_path=None,
                topology_report_path=None,
                notes=[reason],
                warnings=[reason],
                failure_code="esp_union_batch_failed",
                command_log_path=union_command_log_path,
                script_path=union_script_path,
                input_model_path=artifact_source_path,
                provenance={"normalization": normalization_payload},
                artifacts=output_artifacts,
            )
        if not union_export_path.exists():
            reason = (
                "OpenCSM union normalization batch returned success but did not emit "
                f"the expected STEP export at {union_export_path}."
            )
            return EspMaterializationResult(
                status="failed",
                normalized_geometry_path=None,
                topology_report_path=None,
                notes=[reason],
                warnings=[reason],
                failure_code="esp_union_export_missing",
                command_log_path=union_command_log_path,
                script_path=union_script_path,
                input_model_path=artifact_source_path,
                provenance={"normalization": normalization_payload},
                artifacts=output_artifacts,
            )

        union_unit_notes = _rewrite_mislabeled_mm_step_to_meters_if_needed(
            export_path=union_export_path,
            source_path=source_path,
        )
        union_topology = _probe_step_topology(union_export_path, artifact_dir)
        expected_group_count = len(raw_analysis.touching_groups)
        union_validation_errors: list[str] = []
        if union_topology.body_count != expected_group_count:
            union_validation_errors.append(
                "union_volume_count_mismatch:"
                f"expected={expected_group_count},actual={union_topology.body_count}"
            )

        expected_group_bounds: list[tuple[float, float, float, float, float, float]] = []
        raw_body_lookup = {record.body_tag: record for record in raw_analysis.body_records}
        for group in raw_analysis.touching_groups:
            group_boxes = [raw_body_lookup[tag].bbox for tag in group["body_tags"] if tag in raw_body_lookup]
            if not group_boxes:
                continue
            expected_group_bounds.append(
                (
                    min(box[0] for box in group_boxes),
                    min(box[1] for box in group_boxes),
                    min(box[2] for box in group_boxes),
                    max(box[3] for box in group_boxes),
                    max(box[4] for box in group_boxes),
                    max(box[5] for box in group_boxes),
                )
            )

        union_analysis = _analyze_symmetry_touching_solids(union_export_path)
        union_body_records = union_analysis.body_records
        bbox_tol = max(
            max(
                raw_topology.bounds.x_max - raw_topology.bounds.x_min if raw_topology.bounds else 0.0,
                raw_topology.bounds.y_max - raw_topology.bounds.y_min if raw_topology.bounds else 0.0,
                raw_topology.bounds.z_max - raw_topology.bounds.z_min if raw_topology.bounds else 0.0,
                1.0,
            )
            * 2.0e-6,
            1.0e-9,
        )
        remaining_union_bounds = [record.bbox for record in union_body_records]
        for expected_bounds in expected_group_bounds:
            matched_index = None
            for candidate_index, candidate_bounds in enumerate(remaining_union_bounds):
                if _bbox_close(expected_bounds, candidate_bounds, bbox_tol):
                    matched_index = candidate_index
                    break
            if matched_index is None:
                union_validation_errors.append(
                    "union_bbox_mismatch:"
                    f"expected={list(expected_bounds)}"
                )
            else:
                remaining_union_bounds.pop(matched_index)

        if union_validation_errors:
            reason = (
                "OpenCSM union normalization did not preserve the expected wetted-envelope "
                "groups cleanly: " + "; ".join(union_validation_errors)
            )
            return EspMaterializationResult(
                status="failed",
                normalized_geometry_path=None,
                topology_report_path=None,
                notes=[reason],
                warnings=[reason],
                failure_code="esp_union_validation_failed",
                command_log_path=union_command_log_path,
                script_path=union_script_path,
                input_model_path=artifact_source_path,
                provenance={
                    "normalization": {
                        **normalization_payload,
                        "union_topology": union_topology.model_dump(mode="json"),
                        "union_analysis": {
                            "touching_groups": union_analysis.touching_groups,
                            "duplicate_interface_face_pair_count": len(union_analysis.duplicate_face_pairs),
                            "internal_cap_face_count": len(union_analysis.internal_cap_face_tags),
                        },
                        "errors": union_validation_errors,
                    }
                },
                artifacts=output_artifacts,
            )

        if raw_analysis.singleton_body_tags:
            _combine_union_groups_with_singletons(
                raw_step_path=raw_export_path,
                raw_topology=raw_topology,
                singleton_body_tags=raw_analysis.singleton_body_tags,
                union_step_path=union_export_path,
                union_topology=union_topology,
                output_path=export_path,
            )
            normalization_payload["actions"].append("combine_union_groups_with_rescaled_singletons")
            final_notes.append("combined_union_groups_with_rescaled_singletons")
        else:
            shutil.copy2(union_export_path, export_path)
            normalization_payload["actions"].append("promote_union_groups_as_final_geometry")
            final_notes.append("promoted_union_groups_as_final_geometry")

        final_notes.extend(union_unit_notes)
        final_stdout = "\n".join(
            text for text in (completed.stdout or "", union_completed.stdout or "") if text
        )
        final_stderr = "\n".join(
            text for text in (completed.stderr or "", union_completed.stderr or "") if text
        )
        normalization_payload["applied"] = True
        normalization_payload["union_topology"] = union_topology.model_dump(mode="json")
        normalization_payload["union_analysis"] = {
            "touching_groups": union_analysis.touching_groups,
            "singleton_body_tags": union_analysis.singleton_body_tags,
            "grouped_body_tags": union_analysis.grouped_body_tags,
            "duplicate_interface_face_pair_count": len(union_analysis.duplicate_face_pairs),
            "internal_cap_face_count": len(union_analysis.internal_cap_face_tags),
            "notes": union_analysis.notes,
        }
    else:
        shutil.copy2(raw_export_path, export_path)
        normalization_payload["actions"].append("raw_export_already_cfd_clean_enough")
        final_notes.append("normalization_pass_not_needed")

    final_unit_notes = _rewrite_mislabeled_mm_step_to_meters_if_needed(
        export_path=export_path,
        source_path=source_path,
    )
    final_notes.extend(final_unit_notes)
    final_analysis = _analyze_symmetry_touching_solids(export_path)
    normalization_payload["final_analysis"] = {
        "touching_groups": final_analysis.touching_groups,
        "singleton_body_tags": final_analysis.singleton_body_tags,
        "grouped_body_tags": final_analysis.grouped_body_tags,
        "duplicate_interface_face_pair_count": len(final_analysis.duplicate_face_pairs),
        "internal_cap_face_count": len(final_analysis.internal_cap_face_tags),
        "notes": final_analysis.notes,
    }
    if final_analysis.touching_groups or final_analysis.duplicate_face_pairs:
        reason = (
            "Final normalized geometry still contains symmetry-generated touching solids or "
            "duplicate interface faces that would pollute CFD meshing."
        )
        return EspMaterializationResult(
            status="failed",
            normalized_geometry_path=export_path if export_path.exists() else None,
            topology_report_path=None,
            notes=[reason],
            warnings=[reason],
            failure_code="esp_normalized_geometry_not_cfd_clean",
            command_log_path=command_log_path,
            script_path=script_path,
            input_model_path=artifact_source_path,
            provenance={"normalization": normalization_payload},
            artifacts=output_artifacts,
        )

    topology = _write_topology_report(
        report_path=topology_report_path,
        export_path=export_path,
        source_path=source_path,
        input_model_path=artifact_source_path,
        batch_binary=resolved_binary,
        runtime_exec_dir=work_dir,
        stdout=final_stdout,
        stderr=final_stderr,
        extra_notes=[*final_notes, *raw_analysis.notes, *final_analysis.notes],
        extra_payload={"normalization": normalization_payload},
    )
    topology.normalization = {
        **normalization_payload,
        "normalized_counts": {
            "body_count": topology.body_count,
            "surface_count": topology.surface_count,
            "volume_count": topology.volume_count,
        },
    }
    normalization_payload["normalized_counts"] = topology.normalization["normalized_counts"]
    _write_normalization_report(normalization_report_path, normalization_payload)

    provider_version = None
    if completed.stdout:
        first_line = completed.stdout.splitlines()[0].strip() if completed.stdout else ""
        if first_line:
            provider_version = first_line[:120]

    return EspMaterializationResult(
        status="success",
        normalized_geometry_path=export_path,
        topology_report_path=topology_report_path,
        notes=[
            *final_notes,
            f"OpenCSM batch succeeded via {Path(resolved_binary).name}.",
        ],
        warnings=final_warnings,
        failure_code=None,
        provider_version=provider_version,
        command_log_path=command_log_path,
        script_path=script_path,
        input_model_path=artifact_source_path,
        topology=topology,
        provenance={"normalization": normalization_payload},
        artifacts=output_artifacts,
    )
