from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from ..schema import GeometryTopologyMetadata
from .openvsp_surface_intersection import _probe_step_topology

Runner = Callable[[List[str], Path], subprocess.CompletedProcess]

OCSM_SCRIPT_NAME = "rebuild.csm"
EXPORT_FILE_NAME = "normalized.stp"
COMMAND_LOG_NAME = "ocsm.log"
TOPOLOGY_REPORT_NAME = "topology.json"


@dataclass(frozen=True)
class EspMaterializationResult:
    status: str
    normalized_geometry_path: Optional[Path]
    topology_report_path: Optional[Path]
    topology: Optional[GeometryTopologyMetadata] = None
    notes: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    failure_code: Optional[str] = None
    provider_version: Optional[str] = None
    command_log_path: Optional[Path] = None
    script_path: Optional[Path] = None
    input_model_path: Optional[Path] = None


def _default_runner(args: List[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        args,
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=False,
    )


def _resolve_batch_binary() -> Optional[str]:
    for candidate in ("serveCSM", "ocsm"):
        resolved = shutil.which(candidate)
        if resolved is not None:
            return resolved
    return None


def _build_csm_script(source_path: Path, export_path: Path) -> str:
    script_lines = [
        "# Auto-generated by hpa_meshing.providers.esp_pipeline",
        "# Rebuilds OpenVSP model through the official UDPRIM vsp3 bridge",
        f"SET vsp_model_path $\"{source_path}\"",
        f"SET export_path $\"{export_path}\"",
        "UDPRIM vsp3 filename !vsp_model_path",
        "STORE aircraft_assembly",
        "RESTORE aircraft_assembly",
        "DUMP !export_path 0 1",
        "END",
        "",
    ]
    return "\n".join(script_lines)


def _prepare_runtime_dirs(staging_dir: Path) -> tuple[Path, Path]:
    artifact_dir = (staging_dir / "esp_runtime").resolve()
    artifact_dir.mkdir(parents=True, exist_ok=True)
    scratch_root = Path(
        tempfile.mkdtemp(prefix="hpa_esp_runtime_", dir="/tmp")
    ).resolve()
    work_dir = scratch_root / "runtime"
    work_dir.symlink_to(artifact_dir, target_is_directory=True)
    return artifact_dir, work_dir


def _stage_source_model(
    source_path: Path,
    artifact_dir: Path,
    work_dir: Path,
) -> tuple[Path, Path]:
    resolved_source = source_path.resolve()
    artifact_source = (artifact_dir / resolved_source.name).resolve()
    if artifact_source != resolved_source:
        shutil.copy2(resolved_source, artifact_source)
    work_source = work_dir / artifact_source.name
    return artifact_source, work_source


def _write_topology_report(
    *,
    report_path: Path,
    export_path: Path,
    source_path: Path,
    input_model_path: Path,
    batch_binary: str,
    runtime_exec_dir: Path,
    stdout: str,
    stderr: str,
) -> GeometryTopologyMetadata:
    topology = _probe_step_topology(export_path, report_path.parent)
    payload: Dict[str, Any] = topology.model_dump(mode="json")
    payload.update(
        {
        "source_path": str(source_path),
        "input_model_path": str(input_model_path),
        "export_path": str(export_path),
        "export_exists": export_path.exists(),
        "export_size_bytes": export_path.stat().st_size if export_path.exists() else None,
        "batch_binary": batch_binary,
        "runtime_exec_dir": str(runtime_exec_dir),
        "stdout_tail": stdout[-2000:] if stdout else "",
        "stderr_tail": stderr[-2000:] if stderr else "",
        }
    )
    report_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return topology


def _write_command_log(
    *,
    log_path: Path,
    args: List[str],
    returncode: int,
    stdout: str,
    stderr: str,
) -> None:
    log_path.write_text(
        "\n".join(
            [
                "command: " + " ".join(args),
                f"returncode: {returncode}",
                "--- stdout ---",
                stdout,
                "--- stderr ---",
                stderr,
                "",
            ]
        ),
        encoding="utf-8",
    )


def materialize_with_esp(
    *,
    source_path: Path,
    staging_dir: Path,
    runner: Optional[Runner] = None,
    batch_binary: Optional[str] = None,
) -> EspMaterializationResult:
    artifact_dir, work_dir = _prepare_runtime_dirs(staging_dir)

    source_path = source_path.resolve()
    artifact_source_path, work_source_path = _stage_source_model(
        source_path,
        artifact_dir,
        work_dir,
    )
    script_path = (artifact_dir / OCSM_SCRIPT_NAME).resolve()
    export_path = (artifact_dir / EXPORT_FILE_NAME).resolve()
    command_log_path = (artifact_dir / COMMAND_LOG_NAME).resolve()
    topology_report_path = (artifact_dir / TOPOLOGY_REPORT_NAME).resolve()
    work_script_path = work_dir / OCSM_SCRIPT_NAME
    work_export_path = work_dir / EXPORT_FILE_NAME

    script_path.write_text(
        _build_csm_script(source_path=work_source_path, export_path=work_export_path),
        encoding="utf-8",
    )

    resolved_runner = runner or _default_runner
    resolved_binary = batch_binary or _resolve_batch_binary()
    if resolved_binary is None:
        reason = "Neither serveCSM nor ocsm was resolvable on PATH."
        _write_command_log(
            log_path=command_log_path,
            args=[],
            returncode=-1,
            stdout="",
            stderr=reason,
        )
        return EspMaterializationResult(
            status="failed",
            normalized_geometry_path=None,
            topology_report_path=None,
            notes=[reason],
            warnings=[reason],
            failure_code="esp_batch_binary_missing",
            command_log_path=command_log_path,
            script_path=script_path,
            input_model_path=artifact_source_path,
        )

    args = [resolved_binary, "-batch", str(work_script_path)]
    completed = resolved_runner(args, work_dir)

    _write_command_log(
        log_path=command_log_path,
        args=args,
        returncode=completed.returncode,
        stdout=completed.stdout or "",
        stderr=completed.stderr or "",
    )

    if completed.returncode != 0:
        reason = (
            f"OpenCSM batch exited with status {completed.returncode}. "
            "Inspect the command log for serveCSM/ocsm diagnostics."
        )
        return EspMaterializationResult(
            status="failed",
            normalized_geometry_path=None,
            topology_report_path=None,
            notes=[reason],
            warnings=[reason],
            failure_code="esp_ocsm_batch_failed",
            command_log_path=command_log_path,
            script_path=script_path,
            input_model_path=artifact_source_path,
        )

    if not export_path.exists():
        reason = (
            "OpenCSM batch returned success but did not emit the expected normalized "
            f"STEP export at {export_path}."
        )
        return EspMaterializationResult(
            status="failed",
            normalized_geometry_path=None,
            topology_report_path=None,
            notes=[reason],
            warnings=[reason],
            failure_code="esp_export_missing",
            command_log_path=command_log_path,
            script_path=script_path,
            input_model_path=artifact_source_path,
        )

    topology = _write_topology_report(
        report_path=topology_report_path,
        export_path=export_path,
        source_path=source_path,
        input_model_path=artifact_source_path,
        batch_binary=resolved_binary,
        runtime_exec_dir=work_dir,
        stdout=completed.stdout or "",
        stderr=completed.stderr or "",
    )

    provider_version = None
    if completed.stdout:
        first_line = completed.stdout.splitlines()[0].strip() if completed.stdout else ""
        if first_line:
            provider_version = first_line[:120]

    return EspMaterializationResult(
        status="success",
        normalized_geometry_path=export_path,
        topology_report_path=topology_report_path,
        notes=[f"OpenCSM batch succeeded via {Path(resolved_binary).name}."],
        warnings=[],
        failure_code=None,
        provider_version=provider_version,
        command_log_path=command_log_path,
        script_path=script_path,
        input_model_path=artifact_source_path,
        topology=topology,
    )
