from __future__ import annotations

from collections.abc import Callable
import json
from pathlib import Path
from typing import Any, Dict, Literal

from pydantic import BaseModel, Field

from .main_wing_station_seam_profile_resample_strategy_probe import (
    _format_csm_number,
    _materialize_candidate,
    _parse_csm_sections,
)
from .main_wing_station_seam_side_aware_brep_validation_probe import (
    build_main_wing_station_seam_side_aware_brep_validation_probe_report,
)
from .main_wing_station_seam_side_aware_parametrization_probe import (
    _side_parametrized_sections,
    _target_side_counts,
)


SideAwareExportOpcodeVariantStatusType = Literal[
    "side_aware_export_opcode_variant_recovered",
    "side_aware_export_opcode_variant_not_recovered",
    "side_aware_export_opcode_variant_source_only_ready_for_materialization",
    "side_aware_export_opcode_variant_materialization_failed",
    "blocked",
]
VariantMaterializer = Callable[..., Dict[str, Any]]
VariantValidator = Callable[..., Dict[str, Any]]

DEFAULT_OPCODE_VARIANTS = [
    "upper_lower_spline_split",
    "all_linseg",
]


class MainWingStationSeamSideAwareExportOpcodeVariantProbeReport(BaseModel):
    schema_version: Literal[
        "main_wing_station_seam_side_aware_export_opcode_variant_probe.v1"
    ] = "main_wing_station_seam_side_aware_export_opcode_variant_probe.v1"
    component: Literal["main_wing"] = "main_wing"
    execution_scope: Literal[
        "report_only_side_aware_export_opcode_variant_probe"
    ] = "report_only_side_aware_export_opcode_variant_probe"
    production_default_changed: bool = False
    opcode_variant_status: SideAwareExportOpcodeVariantStatusType
    profile_parametrization_audit_path: str
    source_csm_path: str | None = None
    materialize_variants: bool = False
    variants: list[str] = Field(default_factory=list)
    target_station_y_m: list[float] = Field(default_factory=list)
    target_upper_side_point_count: int = 30
    target_lower_side_point_count: int = 30
    surface_count_guard: dict[str, Any] = Field(default_factory=dict)
    variant_reports: list[dict[str, Any]] = Field(default_factory=list)
    variant_summary: dict[str, Any] = Field(default_factory=dict)
    engineering_findings: list[str] = Field(default_factory=list)
    blocking_reasons: list[str] = Field(default_factory=list)
    next_actions: list[str] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def _default_report_root() -> Path:
    return _repo_root() / "hpa_meshing_package" / "docs" / "reports"


def _default_profile_parametrization_audit_path() -> Path:
    return (
        _default_report_root()
        / "main_wing_station_seam_profile_parametrization_audit"
        / "main_wing_station_seam_profile_parametrization_audit.v1.json"
    )


def _load_json(path: Path, blockers: list[str], label: str) -> dict[str, Any] | None:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        blockers.append(f"{label}_missing")
        return None
    except json.JSONDecodeError as exc:
        blockers.append(f"{label}_invalid_json:{exc}")
        return None
    return payload if isinstance(payload, dict) else {}


def _resolve_path(value: Any) -> Path | None:
    if value is None or value == "":
        return None
    path = Path(str(value))
    return path if path.is_absolute() else _repo_root() / path


def _float_list(values: Any) -> list[float]:
    if not isinstance(values, list):
        return []
    result: list[float] = []
    for value in values:
        if isinstance(value, bool):
            continue
        try:
            converted = float(value)
        except (TypeError, ValueError):
            continue
        if converted not in result:
            result.append(converted)
    return result


def _build_variant_csm(
    *,
    sections: list[dict[str, Any]],
    variant: str,
    export_filename: str,
    source_csm_path: Path,
    upper_side_point_count: int,
) -> str:
    leading_edge_point_index = int(upper_side_point_count) - 1
    lines = [
        "# Auto-generated by hpa_meshing.main_wing_station_seam_side_aware_export_opcode_variant_probe",
        "# Report-only opcode variant; not a production provider default",
        f"# Variant: {variant}",
        f"# Source rebuild.csm: {source_csm_path}",
        f"SET export_path $\"{export_filename}\"",
        "",
        "mark",
    ]
    for section in sections:
        points = section.get("points", [])
        if not isinstance(points, list) or len(points) < 4:
            raise ValueError("candidate section points missing")
        lines.append(
            "skbeg " + " ".join(_format_csm_number(value) for value in points[0])
        )
        for point_index, point in enumerate(points[1:], start=1):
            if variant == "all_linseg":
                opcode = "linseg"
            elif variant == "upper_lower_spline_split":
                opcode = (
                    "linseg"
                    if point_index
                    in {1, leading_edge_point_index, len(points) - 1}
                    else "spline"
                )
            else:
                raise ValueError(f"unknown side-aware opcode variant: {variant}")
            lines.append(
                f"   {opcode} "
                + " ".join(_format_csm_number(value) for value in point)
            )
        lines.append("skend")
    lines.extend(
        [
            "rule",
            f"ATTRIBUTE _name $main_wing_side_aware_opcode_{variant}",
            "ATTRIBUTE capsGroup $main_wing",
            "DUMP !export_path 0 1",
            "END",
            "",
        ]
    )
    return "\n".join(lines)


def _materialize_variant(
    *,
    variant: str,
    out_dir: Path,
    csm_text: str,
    timeout_seconds: float,
) -> dict[str, Any]:
    return _materialize_candidate(
        out_dir=out_dir,
        csm_text=csm_text,
        timeout_seconds=timeout_seconds,
        surface_inventory_override=None,
    )


def _validate_variant(
    *,
    candidate_step_path: Path,
    station_y_targets: list[float],
) -> dict[str, Any]:
    report = build_main_wing_station_seam_side_aware_brep_validation_probe_report(
        candidate_step_path=candidate_step_path,
        station_y_targets=station_y_targets,
    )
    return report.model_dump(mode="json")


def _surface_count(topology: dict[str, Any]) -> int | None:
    value = topology.get("surface_count")
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return int(value)
    return None


def _should_skip_validation(
    *,
    topology: dict[str, Any],
    max_surface_count_for_validation: int,
) -> bool:
    surface_count = _surface_count(topology)
    return surface_count is not None and surface_count > max_surface_count_for_validation


def _variant_summary(variant_reports: list[dict[str, Any]]) -> dict[str, Any]:
    recovered = [
        report
        for report in variant_reports
        if report.get("validation", {}).get("probe_status")
        == "side_aware_candidate_station_brep_edges_valid"
    ]
    validated = [
        report
        for report in variant_reports
        if isinstance(report.get("validation"), dict)
        and report.get("validation", {}).get("probe_status") is not None
    ]
    station_edge_counts = [
        int(summary.get("station_edge_check_count"))
        for report in validated
        if isinstance(summary := report.get("validation", {}).get("hotspot_summary"), dict)
        and isinstance(summary.get("station_edge_check_count"), int)
    ]
    return {
        "variant_count": len(variant_reports),
        "materialized_variant_count": sum(
            report.get("materialization", {}).get("status") == "materialized"
            for report in variant_reports
        ),
        "validated_variant_count": len(validated),
        "recovered_variant_count": len(recovered),
        "surface_count_guard_skipped_count": sum(
            report.get("validation_status") == "skipped_surface_count_guard"
            for report in variant_reports
        ),
        "best_station_edge_check_count": (
            max(station_edge_counts) if station_edge_counts else None
        ),
    }


def _status(
    *,
    blockers: list[str],
    materialize_variants: bool,
    variant_reports: list[dict[str, Any]],
    summary: dict[str, Any],
) -> SideAwareExportOpcodeVariantStatusType:
    if blockers:
        return "blocked"
    if not materialize_variants:
        return "side_aware_export_opcode_variant_source_only_ready_for_materialization"
    if int(summary.get("recovered_variant_count") or 0) > 0:
        return "side_aware_export_opcode_variant_recovered"
    if not variant_reports or int(summary.get("materialized_variant_count") or 0) == 0:
        return "side_aware_export_opcode_variant_materialization_failed"
    return "side_aware_export_opcode_variant_not_recovered"


def _engineering_findings(
    *,
    status: SideAwareExportOpcodeVariantStatusType,
    variant_reports: list[dict[str, Any]],
) -> list[str]:
    if status == "blocked":
        return ["side_aware_export_opcode_variant_probe_blocked"]
    findings = ["side_aware_export_opcode_variant_probe_evaluated"]
    for report in variant_reports:
        variant = report.get("variant")
        topology = report.get("materialization", {}).get("topology", {})
        surface_count = _surface_count(topology if isinstance(topology, dict) else {})
        validation = report.get("validation", {})
        if variant == "all_linseg" and report.get("validation_status") == "skipped_surface_count_guard":
            findings.append("all_linseg_surface_count_explosion_observed")
        if (
            variant == "upper_lower_spline_split"
            and isinstance(validation, dict)
            and validation.get("probe_status")
            == "side_aware_candidate_station_brep_edges_suspect"
        ):
            findings.append("upper_lower_spline_split_still_pcurve_suspect")
        if surface_count is not None and surface_count > 0:
            findings.append(f"{variant}_surface_count_{surface_count}")
    if status == "side_aware_export_opcode_variant_recovered":
        findings.append("side_aware_export_opcode_variant_recovered_brep_gate")
    elif status == "side_aware_export_opcode_variant_not_recovered":
        findings.append("simple_opcode_variants_do_not_recover_station_pcurve_gate")
    return list(dict.fromkeys(findings))


def _blocking_reasons(
    status: SideAwareExportOpcodeVariantStatusType,
    blockers: list[str],
) -> list[str]:
    reasons = list(blockers)
    if status == "side_aware_export_opcode_variant_not_recovered":
        reasons.append("side_aware_export_opcode_variants_not_recovered")
        reasons.append("side_aware_candidate_mesh_handoff_not_run")
    if status == "side_aware_export_opcode_variant_materialization_failed":
        reasons.append("side_aware_export_opcode_variant_materialization_failed")
    if status == "blocked" and not reasons:
        reasons.append("side_aware_export_opcode_variant_probe_blocked")
    return list(dict.fromkeys(reasons))


def _next_actions(status: SideAwareExportOpcodeVariantStatusType) -> list[str]:
    if status == "side_aware_export_opcode_variant_recovered":
        return [
            "rerun_projected_pcurve_builder_on_recovered_opcode_variant",
            "rerun_mesh_handoff_only_after_station_metadata_gate_passes",
        ]
    if status == "side_aware_export_opcode_variant_not_recovered":
        return [
            "inspect_export_pcurve_metadata_generation_instead_of_simple_opcode_variants",
            "avoid_all_linseg_surface_count_explosion_as_product_candidate",
            "do_not_advance_to_mesh_until_station_brep_gate_passes",
        ]
    if status == "side_aware_export_opcode_variant_source_only_ready_for_materialization":
        return ["materialize_side_aware_export_opcode_variants"]
    if status == "side_aware_export_opcode_variant_materialization_failed":
        return ["inspect_opcode_variant_ocsm_logs"]
    return ["restore_side_aware_export_opcode_variant_inputs"]


def build_main_wing_station_seam_side_aware_export_opcode_variant_probe_report(
    *,
    profile_parametrization_audit_path: Path | None = None,
    variants: list[str] | None = None,
    materialize_variants: bool = False,
    materialization_root: Path | None = None,
    timeout_seconds: float = 120.0,
    max_surface_count_for_validation: int = 128,
    target_upper_side_point_count: int = 30,
    target_lower_side_point_count: int = 30,
    variant_materializer: VariantMaterializer | None = None,
    variant_validator: VariantValidator | None = None,
) -> MainWingStationSeamSideAwareExportOpcodeVariantProbeReport:
    audit_path = (
        _default_profile_parametrization_audit_path()
        if profile_parametrization_audit_path is None
        else profile_parametrization_audit_path
    )
    selected_variants = variants or DEFAULT_OPCODE_VARIANTS
    blockers: list[str] = []
    audit_payload = _load_json(audit_path, blockers, "profile_parametrization_audit")
    source_csm_path = _resolve_path(
        audit_payload.get("source_csm_path") if isinstance(audit_payload, dict) else None
    )
    if source_csm_path is None:
        blockers.append("source_csm_path_missing")
    elif not source_csm_path.exists():
        blockers.append("source_csm_missing")
    target_station_y_m = _float_list(
        audit_payload.get("target_station_y_m") if isinstance(audit_payload, dict) else []
    )
    if not target_station_y_m:
        blockers.append("target_station_y_missing")
    sections = _parse_csm_sections(source_csm_path, blockers) if source_csm_path else []
    variant_reports: list[dict[str, Any]] = []
    if not blockers:
        upper_target, lower_target = _target_side_counts(
            sections,
            target_upper_side_point_count=target_upper_side_point_count,
            target_lower_side_point_count=target_lower_side_point_count,
        )
        side_sections, _, side_summary = _side_parametrized_sections(
            sections,
            upper_target_count=upper_target,
            lower_target_count=lower_target,
        )
        root = (
            _default_report_root()
            / "main_wing_station_seam_side_aware_export_opcode_variant_probe"
            if materialization_root is None
            else materialization_root
        )
        materializer = variant_materializer or _materialize_variant
        validator = variant_validator or _validate_variant
        for variant in selected_variants:
            out_dir = root / variant
            csm_text = _build_variant_csm(
                sections=side_sections,
                variant=variant,
                export_filename="candidate_raw_dump.stp",
                source_csm_path=source_csm_path,
                upper_side_point_count=upper_target,
            )
            materialization: dict[str, Any] = {
                "status": "not_requested",
                "candidate_csm_text_available": True,
            }
            validation: dict[str, Any] = {}
            validation_status = "not_requested"
            if materialize_variants:
                materialization = materializer(
                    variant=variant,
                    out_dir=out_dir,
                    csm_text=csm_text,
                    timeout_seconds=timeout_seconds,
                )
                topology = materialization.get("topology", {})
                topology = topology if isinstance(topology, dict) else {}
                if materialization.get("status") != "materialized":
                    validation_status = "not_run_materialization_failed"
                elif _should_skip_validation(
                    topology=topology,
                    max_surface_count_for_validation=max_surface_count_for_validation,
                ):
                    validation_status = "skipped_surface_count_guard"
                else:
                    step_path = Path(str(materialization.get("step_path")))
                    validation = validator(
                        candidate_step_path=step_path,
                        station_y_targets=target_station_y_m,
                    )
                    validation_status = str(validation.get("probe_status"))
            variant_reports.append(
                {
                    "variant": variant,
                    "opcode_policy": (
                        "all_profile_segments_linseg"
                        if variant == "all_linseg"
                        else "split_upper_lower_spline_at_le_anchor"
                    ),
                    "side_parametrization_summary": side_summary,
                    "materialization": materialization,
                    "validation_status": validation_status,
                    "validation": validation,
                }
            )
    summary = _variant_summary(variant_reports)
    status = _status(
        blockers=blockers,
        materialize_variants=materialize_variants,
        variant_reports=variant_reports,
        summary=summary,
    )
    return MainWingStationSeamSideAwareExportOpcodeVariantProbeReport(
        opcode_variant_status=status,
        profile_parametrization_audit_path=str(audit_path),
        source_csm_path=str(source_csm_path) if source_csm_path else None,
        materialize_variants=materialize_variants,
        variants=list(selected_variants),
        target_station_y_m=target_station_y_m,
        target_upper_side_point_count=target_upper_side_point_count,
        target_lower_side_point_count=target_lower_side_point_count,
        surface_count_guard={
            "max_surface_count_for_validation": int(max_surface_count_for_validation),
            "validation_skipped_when_surface_count_exceeds_guard": True,
        },
        variant_reports=variant_reports,
        variant_summary=summary,
        engineering_findings=_engineering_findings(
            status=status,
            variant_reports=variant_reports,
        ),
        blocking_reasons=_blocking_reasons(status, blockers),
        next_actions=_next_actions(status),
        limitations=[
            "This probe changes only report-local CSM candidates; it does not change provider defaults.",
            "Opcode variants are upstream export diagnostics, not mesh handoff or solver evidence.",
            "High surface-count variants are guarded before BRep validation to avoid promoting faceted candidates.",
        ],
    )


def write_main_wing_station_seam_side_aware_export_opcode_variant_probe_report(
    out_dir: Path,
    *,
    report: MainWingStationSeamSideAwareExportOpcodeVariantProbeReport | None = None,
    profile_parametrization_audit_path: Path | None = None,
    variants: list[str] | None = None,
    materialize_variants: bool = False,
    materialization_root: Path | None = None,
    timeout_seconds: float = 120.0,
    max_surface_count_for_validation: int = 128,
    target_upper_side_point_count: int = 30,
    target_lower_side_point_count: int = 30,
    variant_materializer: VariantMaterializer | None = None,
    variant_validator: VariantValidator | None = None,
) -> dict[str, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    if report is None:
        report = build_main_wing_station_seam_side_aware_export_opcode_variant_probe_report(
            profile_parametrization_audit_path=profile_parametrization_audit_path,
            variants=variants,
            materialize_variants=materialize_variants,
            materialization_root=materialization_root,
            timeout_seconds=timeout_seconds,
            max_surface_count_for_validation=max_surface_count_for_validation,
            target_upper_side_point_count=target_upper_side_point_count,
            target_lower_side_point_count=target_lower_side_point_count,
            variant_materializer=variant_materializer,
            variant_validator=variant_validator,
        )
    json_path = out_dir / "main_wing_station_seam_side_aware_export_opcode_variant_probe.v1.json"
    markdown_path = out_dir / "main_wing_station_seam_side_aware_export_opcode_variant_probe.v1.md"
    json_path.write_text(
        json.dumps(report.model_dump(mode="json"), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    lines = [
        "# Main Wing Station Seam Side-Aware Export Opcode Variant Probe v1",
        "",
        f"- status: `{report.opcode_variant_status}`",
        f"- production_default_changed: `{report.production_default_changed}`",
        f"- source_csm_path: `{report.source_csm_path}`",
        f"- variants: `{', '.join(report.variants)}`",
        f"- materialize_variants: `{report.materialize_variants}`",
        f"- variant_summary: `{json.dumps(report.variant_summary, ensure_ascii=False)}`",
        "",
        "## Engineering Findings",
        "",
    ]
    lines.extend(f"- `{finding}`" for finding in report.engineering_findings)
    lines.extend(["", "## Blocking Reasons", ""])
    lines.extend(f"- `{reason}`" for reason in report.blocking_reasons)
    lines.extend(["", "## Next Actions", ""])
    lines.extend(f"- `{action}`" for action in report.next_actions)
    lines.extend(["", "## Limitations", ""])
    lines.extend(f"- {item}" for item in report.limitations)
    markdown_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return {"json": json_path, "markdown": markdown_path}
