"""Physics-first dual-beam mainline analysis kernel."""

from hpa_mdo.structure.dual_beam_mainline.api import (
    build_dual_beam_mainline_model,
    run_dual_beam_mainline_analysis,
    run_dual_beam_mainline_kernel,
)
from hpa_mdo.structure.dual_beam_mainline.types import (
    AnalysisModeDefinition,
    AnalysisModeName,
    AnalysisOwnership,
    BeamLine,
    ConstraintAssemblyResult,
    DualBeamConstraintMode,
    DualBeamMainlineModel,
    DualBeamMainlineResult,
    EquivalentGateResult,
    FeasibilitySummary,
    GeometryValidityMargins,
    LinkMode,
    LoadSplitResult,
    OptimizerFacingMetrics,
    ReactionRecoveryResult,
    RecoveryResult,
    ReportMetrics,
    RootBCMode,
    SmoothAggregationResult,
    SmoothScaleConfig,
    TorqueInputDefinition,
    TorqueReferenceMode,
    WireBCMode,
    get_analysis_mode_definition,
)

__all__ = [
    "AnalysisModeDefinition",
    "AnalysisModeName",
    "AnalysisOwnership",
    "BeamLine",
    "ConstraintAssemblyResult",
    "DualBeamConstraintMode",
    "DualBeamMainlineModel",
    "DualBeamMainlineResult",
    "EquivalentGateResult",
    "FeasibilitySummary",
    "GeometryValidityMargins",
    "LinkMode",
    "LoadSplitResult",
    "OptimizerFacingMetrics",
    "ReactionRecoveryResult",
    "RecoveryResult",
    "ReportMetrics",
    "RootBCMode",
    "SmoothAggregationResult",
    "SmoothScaleConfig",
    "TorqueInputDefinition",
    "TorqueReferenceMode",
    "WireBCMode",
    "build_dual_beam_mainline_model",
    "get_analysis_mode_definition",
    "run_dual_beam_mainline_analysis",
    "run_dual_beam_mainline_kernel",
]
